/* ALAQ service worker — hors ligne complet
   Stratégie :
   - index.html / navigation : réseau d'abord (toujours la dernière version en ligne),
     cache en secours (avion, mosquée sans réseau…)
   - audios, polices, icônes : cache d'abord (rapide), réseau en secours
   - les audios de la voix de Myriam sont pré-chargés à l'installation
   - la RÉCITATION n'est plus hébergée ici : elle est streamée depuis cdn.islamic.network
     et mise en cache au fil des versets écoutés (voir VOIX dans index.html) */
const CACHE='alaq-v78-2026-08-07d';  // L'APP : versionné, purgé à chaque livraison
/* LES MÉDIAS : un cache À PART, JAMAIS purgé. Un mp3 ne change pas de contenu —
   ba-fatha-son-court.mp3 dira la même chose dans dix ans. Les ranger dans le cache
   versionné revenait à les jeter et à les racheter (8 Mo) à CHAQUE déploiement, sur
   chaque appareil. Ici ils se téléchargent une seule fois dans la vie de l'appareil. */
const MEDIA='alaq-medias';
const CORE=['.','index.html','manifest.webmanifest','icon-192.png','icon-512.png','apple-touch-icon.png'];
const IMAGES=[ // icônes des disques de l'accueil — sans elles les disques sont vides
"images-app-alaq/icone-alaq-bilan.png",
"images-app-alaq/icone-alaq-decouvrir.png",
"images-app-alaq/icone-alaq-ecrire.png",
"images-app-alaq/icone-alaq-lire.png",
"images-app-alaq/icone-alaq-memoriser.png",
"images-app-alaq/icone-alaq-qoran.png",
"images-app-alaq/icone-alaq-reviser.png"
];
const AUDIOS=[
"audios-app-alaq/ain-alif-son-prolonge.mp3",
"audios-app-alaq/ain-damma-son-court.mp3",
"audios-app-alaq/ain-fatha-son-court.mp3",
"audios-app-alaq/ain-isolee-nom-de-la-lettre.mp3",
"audios-app-alaq/ain-kasra-son-court.mp3",
"audios-app-alaq/ain-waw-son-prolonge.mp3",
"audios-app-alaq/ain-ya-son-prolonge.mp3",
"audios-app-alaq/alif-alif-son-prolonge.mp3",
"audios-app-alaq/alif-damma-son-court.mp3",
"audios-app-alaq/alif-fatha-son-court.mp3",
"audios-app-alaq/alif-isolee-nom-de-la-lettre.mp3",
"audios-app-alaq/alif-kasra-son-court.mp3",
"audios-app-alaq/alif-waw-son-prolonge.mp3",
"audios-app-alaq/alif-ya-son-prolonge.mp3",
"audios-app-alaq/ba-alif-son-prolonge.mp3",
"audios-app-alaq/ba-damma-son-court.mp3",
"audios-app-alaq/ba-fatha-son-court.mp3",
"audios-app-alaq/ba-isolee-nom-de-la-lettre.mp3",
"audios-app-alaq/ba-kasra-son-court.mp3",
"audios-app-alaq/ba-waw-son-prolonge.mp3",
"audios-app-alaq/ba-ya-son-prolonge.mp3",
"audios-app-alaq/dad-alif-son-prolonge.mp3",
"audios-app-alaq/dad-damma-son-court.mp3",
"audios-app-alaq/dad-fatha-son-court.mp3",
"audios-app-alaq/dad-kasra-son-court.mp3",
"audios-app-alaq/dad-waw-son-prolonge.mp3",
"audios-app-alaq/dad-ya-son-prolonge.mp3",
"audios-app-alaq/dal-alif-son-prolonge.mp3",
"audios-app-alaq/dal-damma-son-court.mp3",
"audios-app-alaq/dal-fatha-son-court.mp3",
"audios-app-alaq/dal-kasra-son-court.mp3",
"audios-app-alaq/dal-waw-son-prolonge.mp3",
"audios-app-alaq/dal-ya-son-prolonge.mp3",
"audios-app-alaq/dhal-alif-son-prolonge.mp3",
"audios-app-alaq/dhal-damma-son-court.mp3",
"audios-app-alaq/dhal-fatha-son-court.mp3",
"audios-app-alaq/dhal-kasra-son-court.mp3",
"audios-app-alaq/dhal-waw-son-prolonge.mp3",
"audios-app-alaq/dhal-ya-son-prolonge.mp3",
"audios-app-alaq/ghayn-alif-son-prolonge.mp3",
"audios-app-alaq/ghayn-damma-son-court.mp3",
"audios-app-alaq/ghayn-fatha-son-court.mp3",
"audios-app-alaq/ghayn-kasra-son-court.mp3",
"audios-app-alaq/ghayn-waw-son-prolonge.mp3",
"audios-app-alaq/ghayn-ya-son-prolonge.mp3",
"audios-app-alaq/ha-alif-son-prolonge.mp3",
"audios-app-alaq/ha-damma-son-court.mp3",
"audios-app-alaq/ha-fatha-son-court.mp3",
"audios-app-alaq/ha-kasra-son-court.mp3",
"audios-app-alaq/ha-waw-son-prolonge.mp3",
"audios-app-alaq/ha-ya-son-prolonge.mp3",
"audios-app-alaq/hamza-isolee-nom-de-la-lettre.mp3",
"audios-app-alaq/hha-alif-son-prolonge.mp3",
"audios-app-alaq/hha-damma-son-court.mp3",
"audios-app-alaq/hha-fatha-son-court.mp3",
"audios-app-alaq/hha-kasra-son-court.mp3",
"audios-app-alaq/hha-waw-son-prolonge.mp3",
"audios-app-alaq/hha-ya-son-prolonge.mp3",
// ===== lot « marque sonore » du 05/08/2026 : 19 consignes + 29 lettres × 2 voix,
// les 4 félicitations du combo × 2 voix, et le son de fin de leçon =====
"audios-app-alaq/lettre-alif-nom-f.mp3",
"audios-app-alaq/lettre-ba-nom-f.mp3",
"audios-app-alaq/lettre-ta-nom-f.mp3",
"audios-app-alaq/lettre-tha-nom-f.mp3",
"audios-app-alaq/lettre-jim-nom-f.mp3",
"audios-app-alaq/lettre-hha-nom-f.mp3",
"audios-app-alaq/lettre-kha-nom-f.mp3",
"audios-app-alaq/lettre-dal-nom-f.mp3",
"audios-app-alaq/lettre-dhal-nom-f.mp3",
"audios-app-alaq/lettre-ra-nom-f.mp3",
"audios-app-alaq/lettre-zay-nom-f.mp3",
"audios-app-alaq/lettre-sin-nom-f.mp3",
"audios-app-alaq/lettre-shin-nom-f.mp3",
"audios-app-alaq/lettre-sad-nom-f.mp3",
"audios-app-alaq/lettre-dad-nom-f.mp3",
"audios-app-alaq/lettre-tta-nom-f.mp3",
"audios-app-alaq/lettre-dha-nom-f.mp3",
"audios-app-alaq/lettre-ayn-nom-f.mp3",
"audios-app-alaq/lettre-ghayn-nom-f.mp3",
"audios-app-alaq/lettre-fa-nom-f.mp3",
"audios-app-alaq/lettre-qaf-nom-f.mp3",
"audios-app-alaq/lettre-kaf-nom-f.mp3",
"audios-app-alaq/lettre-lam-nom-f.mp3",
"audios-app-alaq/lettre-mim-nom-f.mp3",
"audios-app-alaq/lettre-nun-nom-f.mp3",
"audios-app-alaq/lettre-ha-nom-f.mp3",
"audios-app-alaq/lettre-waw-nom-f.mp3",
"audios-app-alaq/lettre-ya-nom-f.mp3",
"audios-app-alaq/lettre-hamza-nom-f.mp3",
"audios-app-alaq/felicit-moumtaz-f.mp3",
"audios-app-alaq/felicit-sahih-f.mp3",
"audios-app-alaq/felicit-rai-f.mp3",
"audios-app-alaq/felicit-allahumma-barik-f.mp3",
"audios-app-alaq/lettre-alif-nom-h.mp3",
"audios-app-alaq/lettre-ba-nom-h.mp3",
"audios-app-alaq/lettre-ta-nom-h.mp3",
"audios-app-alaq/lettre-tha-nom-h.mp3",
"audios-app-alaq/lettre-jim-nom-h.mp3",
"audios-app-alaq/lettre-hha-nom-h.mp3",
"audios-app-alaq/lettre-kha-nom-h.mp3",
"audios-app-alaq/lettre-dal-nom-h.mp3",
"audios-app-alaq/lettre-dhal-nom-h.mp3",
"audios-app-alaq/lettre-ra-nom-h.mp3",
"audios-app-alaq/lettre-zay-nom-h.mp3",
"audios-app-alaq/lettre-sin-nom-h.mp3",
"audios-app-alaq/lettre-shin-nom-h.mp3",
"audios-app-alaq/lettre-sad-nom-h.mp3",
"audios-app-alaq/lettre-dad-nom-h.mp3",
"audios-app-alaq/lettre-tta-nom-h.mp3",
"audios-app-alaq/lettre-dha-nom-h.mp3",
"audios-app-alaq/lettre-ayn-nom-h.mp3",
"audios-app-alaq/lettre-ghayn-nom-h.mp3",
"audios-app-alaq/lettre-fa-nom-h.mp3",
"audios-app-alaq/lettre-qaf-nom-h.mp3",
"audios-app-alaq/lettre-kaf-nom-h.mp3",
"audios-app-alaq/lettre-lam-nom-h.mp3",
"audios-app-alaq/lettre-mim-nom-h.mp3",
"audios-app-alaq/lettre-nun-nom-h.mp3",
"audios-app-alaq/lettre-ha-nom-h.mp3",
"audios-app-alaq/lettre-waw-nom-h.mp3",
"audios-app-alaq/lettre-ya-nom-h.mp3",
"audios-app-alaq/lettre-hamza-nom-h.mp3",
"audios-app-alaq/felicit-moumtaz-h.mp3",
"audios-app-alaq/felicit-sahih-h.mp3",
"audios-app-alaq/felicit-rai-h.mp3",
"audios-app-alaq/felicit-allahumma-barik-h.mp3",
"audios-app-alaq/sfx-fin-lecon.mp3",
"audios-app-alaq/instr-assoc-haraka.mp3",
"audios-app-alaq/instr-associe.mp3",
"audios-app-alaq/instr-attache-6-dorees.mp3",
"audios-app-alaq/instr-attache-6.mp3",
"audios-app-alaq/instr-choisis.mp3",
"audios-app-alaq/instr-combine.mp3",
"audios-app-alaq/instr-costume-glisse.mp3",
"audios-app-alaq/instr-costumes.mp3",
"audios-app-alaq/instr-deux-fois-cartes.mp3",
"audios-app-alaq/instr-dragassoc.mp3",
"audios-app-alaq/instr-dragmad.mp3",
"audios-app-alaq/instr-ecoute-reponse.mp3",
"audios-app-alaq/instr-ecris-arabe.mp3",
"audios-app-alaq/instr-ecris-ecoute.mp3",
"audios-app-alaq/instr-explore-3.mp3",
"audios-app-alaq/instr-explore-cases.mp3",
"audios-app-alaq/instr-glisse-gd.mp3",
"audios-app-alaq/instr-haraka-intro.mp3",
"audios-app-alaq/instr-hp-choisis.mp3",
"audios-app-alaq/instr-info-chedda.mp3",
"audios-app-alaq/instr-info-lettres-empilees.mp3",
"audios-app-alaq/instr-info-soukoun.mp3",
"audios-app-alaq/instr-info-tanwin.mp3",
"audios-app-alaq/instr-intro-28-lettres.mp3",
"audios-app-alaq/instr-intro-bienvenue.mp3",
"audios-app-alaq/instr-intro-quiz.mp3",
"audios-app-alaq/instr-lettre-nom.mp3",
"audios-app-alaq/instr-madrasatoun.mp3",
"audios-app-alaq/instr-mot-ecoute.mp3",
"audios-app-alaq/instr-prolong-deux.mp3",
"audios-app-alaq/instr-prolong-dorees.mp3",
"audios-app-alaq/instr-prolong-intro.mp3",
"audios-app-alaq/instr-recite.mp3",
"audios-app-alaq/instr-son-long.mp3",
"audios-app-alaq/instr-spot-verset.mp3",
"audios-app-alaq/instr-stiles.mp3",
"audios-app-alaq/instr-touche-droite.mp3",
"audios-app-alaq/instr-trace.mp3",
"audios-app-alaq/instr-vtiles.mp3",
"audios-app-alaq/instr-vwrite.mp3",
"audios-app-alaq/kaf-alif-son-prolonge.mp3",
"audios-app-alaq/kaf-damma-son-court.mp3",
"audios-app-alaq/kaf-fatha-son-court.mp3",
"audios-app-alaq/kaf-kasra-son-court.mp3",
"audios-app-alaq/kaf-waw-son-prolonge.mp3",
"audios-app-alaq/kaf-ya-son-prolonge.mp3",
"audios-app-alaq/lam-alif-son-prolonge.mp3",
"audios-app-alaq/lam-damma-son-court.mp3",
"audios-app-alaq/lam-fatha-son-court.mp3",
"audios-app-alaq/lam-isolee-nom-de-la-lettre.mp3",
"audios-app-alaq/lam-kasra-son-court.mp3",
"audios-app-alaq/lam-waw-son-prolonge.mp3",
"audios-app-alaq/lam-ya-son-prolonge.mp3",
"audios-app-alaq/lettre-alif-nom.mp3",
"audios-app-alaq/lettre-ayn-nom.mp3",
"audios-app-alaq/lettre-ba-nom.mp3",
"audios-app-alaq/lettre-dad-nom.mp3",
"audios-app-alaq/lettre-dal-nom.mp3",
"audios-app-alaq/lettre-dha-nom.mp3",
"audios-app-alaq/lettre-dhal-nom.mp3",
"audios-app-alaq/lettre-fa-nom.mp3",
"audios-app-alaq/lettre-ghayn-nom.mp3",
"audios-app-alaq/lettre-ha-nom.mp3",
"audios-app-alaq/lettre-hamza-nom.mp3",
"audios-app-alaq/lettre-hha-nom.mp3",
"audios-app-alaq/lettre-jim-nom.mp3",
"audios-app-alaq/lettre-kaf-nom.mp3",
"audios-app-alaq/lettre-kha-nom.mp3",
"audios-app-alaq/lettre-lam-nom.mp3",
"audios-app-alaq/lettre-mim-nom.mp3",
"audios-app-alaq/lettre-nun-nom.mp3",
"audios-app-alaq/lettre-qaf-nom.mp3",
"audios-app-alaq/lettre-ra-nom.mp3",
"audios-app-alaq/lettre-sad-nom.mp3",
"audios-app-alaq/lettre-shin-nom.mp3",
"audios-app-alaq/lettre-sin-nom.mp3",
"audios-app-alaq/lettre-ta-nom.mp3",
"audios-app-alaq/lettre-tha-nom.mp3",
"audios-app-alaq/lettre-tta-nom.mp3",
"audios-app-alaq/lettre-waw-nom.mp3",
"audios-app-alaq/lettre-ya-nom.mp3",
"audios-app-alaq/lettre-zay-nom.mp3",
"audios-app-alaq/mim-alif-son-prolonge.mp3",
"audios-app-alaq/mim-damma-son-court.mp3",
"audios-app-alaq/mim-fatha-son-court.mp3",
"audios-app-alaq/mim-isolee-nom-de-la-lettre.mp3",
"audios-app-alaq/mim-kasra-son-court.mp3",
"audios-app-alaq/mim-waw-son-prolonge.mp3",
"audios-app-alaq/mim-ya-son-prolonge.mp3",
"audios-app-alaq/mot-aalim.mp3",
"audios-app-alaq/mot-addallin.mp3",
"audios-app-alaq/mot-ahad.mp3",
"audios-app-alaq/mot-alam.mp3",
"audios-app-alaq/mot-alamoun.mp3",
"audios-app-alaq/mot-alayhim.mp3",
"audios-app-alaq/mot-alhamdu.mp3",
"audios-app-alaq/mot-alim.mp3",
"audios-app-alaq/mot-alladhina.mp3",
"audios-app-alaq/mot-allah.mp3",
"audios-app-alaq/mot-almaghdub.mp3",
"audios-app-alaq/mot-amal.mp3",
"audios-app-alaq/mot-aman.mp3",
"audios-app-alaq/mot-amin.mp3",
"audios-app-alaq/mot-amr.mp3",
"audios-app-alaq/mot-anamta.mp3",
"audios-app-alaq/mot-annas.mp3",
"audios-app-alaq/mot-arabi.mp3",
"audios-app-alaq/mot-arrahim.mp3",
"audios-app-alaq/mot-arrahman.mp3",
"audios-app-alaq/mot-assamad.mp3",
"audios-app-alaq/mot-audhu.mp3",
"audios-app-alaq/mot-ayn.mp3",
"audios-app-alaq/mot-bab.mp3",
"audios-app-alaq/mot-bismi.mp3",
"audios-app-alaq/mot-dars.mp3",
"audios-app-alaq/mot-dhahaba.mp3",
"audios-app-alaq/mot-din.mp3",
"audios-app-alaq/mot-ghasiq.mp3",
"audios-app-alaq/mot-ghayb.mp3",
"audios-app-alaq/mot-ghayr.mp3",
"audios-app-alaq/mot-hasid.mp3",
"audios-app-alaq/mot-hatab.mp3",
"audios-app-alaq/mot-huwa.mp3",
"audios-app-alaq/mot-idha.mp3",
"audios-app-alaq/mot-ihdina.mp3",
"audios-app-alaq/mot-ilah.mp3",
"audios-app-alaq/mot-iman.mp3",
"audios-app-alaq/mot-iyyaka.mp3",
"audios-app-alaq/mot-karim.mp3",
"audios-app-alaq/mot-kasaba.mp3",
"audios-app-alaq/mot-laban.mp3",
"audios-app-alaq/mot-lamma.mp3",
"audios-app-alaq/mot-lawm.mp3",
"audios-app-alaq/mot-lawn.mp3",
"audios-app-alaq/mot-layl.mp3",
"audios-app-alaq/mot-lin.mp3",
"audios-app-alaq/mot-maalik.mp3",
"audios-app-alaq/mot-madrasatoun.mp3",
"audios-app-alaq/mot-mal.mp3",
"audios-app-alaq/mot-malik.mp3",
"audios-app-alaq/mot-mamnoun.mp3",
"audios-app-alaq/mot-manal.mp3",
"audios-app-alaq/mot-manam.mp3",
"audios-app-alaq/mot-mann.mp3",
"audios-app-alaq/mot-mustaqim.mp3",
"audios-app-alaq/mot-naabudu.mp3",
"audios-app-alaq/mot-nabi.mp3",
"audios-app-alaq/mot-naml.mp3",
"audios-app-alaq/mot-nastain.mp3",
"audios-app-alaq/mot-nil.mp3",
"audios-app-alaq/mot-noun.mp3",
"audios-app-alaq/mot-oulama.mp3",
"audios-app-alaq/mot-qul.mp3",
"audios-app-alaq/mot-rabb.mp3",
"audios-app-alaq/mot-rabi.mp3",
"audios-app-alaq/mot-sabr.mp3",
"audios-app-alaq/mot-sirat.mp3",
"audios-app-alaq/mot-sudur.mp3",
"audios-app-alaq/mot-tabba.mp3",
"audios-app-alaq/mot-tariq.mp3",
"audios-app-alaq/mot-umm.mp3",
"audios-app-alaq/mot-umr.mp3",
"audios-app-alaq/mot-uqad.mp3",
"audios-app-alaq/mot-waqaba.mp3",
"audios-app-alaq/mot-yamin.mp3",
"audios-app-alaq/mot-yawm.mp3",
"audios-app-alaq/nom-alalim.mp3",
"audios-app-alaq/nom-almalik.mp3",
"audios-app-alaq/nom-almumin.mp3",
"audios-app-alaq/nom-arrahim.mp3",
"audios-app-alaq/nom-arrahman.mp3",
"audios-app-alaq/nom-assalam.mp3",
"audios-app-alaq/nom-addarr.mp3",
"audios-app-alaq/nom-aladl.mp3",
"audios-app-alaq/nom-alaliyy.mp3",
"audios-app-alaq/nom-alawwal.mp3",
"audios-app-alaq/nom-albadi.mp3",
"audios-app-alaq/nom-albaqi.mp3",
"audios-app-alaq/nom-albari.mp3",
"audios-app-alaq/nom-albarr.mp3",
"audios-app-alaq/nom-albasir.mp3",
"audios-app-alaq/nom-albasit.mp3",
"audios-app-alaq/nom-albatin.mp3",
"audios-app-alaq/nom-alghaniyy.mp3",
"audios-app-alaq/nom-alhadi.mp3",
"audios-app-alaq/nom-alhakam.mp3",
"audios-app-alaq/nom-alhakim.mp3",
"audios-app-alaq/nom-alhalim.mp3",
"audios-app-alaq/nom-alhamid.mp3",
"audios-app-alaq/nom-alhaqq.mp3",
"audios-app-alaq/nom-alhasib.mp3",
"audios-app-alaq/nom-alhayy.mp3",
"audios-app-alaq/nom-alkabir.mp3",
"audios-app-alaq/nom-alkarim.mp3",
"audios-app-alaq/nom-allah.mp3",
"audios-app-alaq/nom-almani.mp3",
"audios-app-alaq/nom-almatin.mp3",
"audios-app-alaq/nom-almubdi.mp3",
"audios-app-alaq/nom-almudhill.mp3",
"audios-app-alaq/nom-almughni.mp3",
"audios-app-alaq/nom-almuhaymin.mp3",
"audios-app-alaq/nom-almuhsi.mp3",
"audios-app-alaq/nom-almuhyi.mp3",
"audios-app-alaq/nom-almuid.mp3",
"audios-app-alaq/nom-almumit.mp3",
"audios-app-alaq/nom-almuntaqim.mp3",
"audios-app-alaq/nom-almuqaddim.mp3",
"audios-app-alaq/nom-almuqit.mp3",
"audios-app-alaq/nom-almuqsit.mp3",
"audios-app-alaq/nom-almuqtadir.mp3",
"audios-app-alaq/nom-almusawwir.mp3",
"audios-app-alaq/nom-almutaali.mp3",
"audios-app-alaq/nom-almutakabbir.mp3",
"audios-app-alaq/nom-alqabid.mp3",
"audios-app-alaq/nom-alqadir.mp3",
"audios-app-alaq/nom-alqahhar.mp3",
"audios-app-alaq/nom-alqawiyy.mp3",
"audios-app-alaq/nom-alqayyum.mp3",
"audios-app-alaq/nom-alquddus.mp3",
"audios-app-alaq/nom-alwadud.mp3",
"audios-app-alaq/nom-alwahhab.mp3",
"audios-app-alaq/nom-alwahid.mp3",
"audios-app-alaq/nom-alwakil.mp3",
"audios-app-alaq/nom-alwali.mp3",
"audios-app-alaq/nom-alwaliyy.mp3",
"audios-app-alaq/nom-alwasi.mp3",
"audios-app-alaq/nom-annur.mp3",
"audios-app-alaq/nom-arraqib.mp3",
"audios-app-alaq/nom-assabur.mp3",
"audios-app-alaq/nom-assamad.mp3",
"audios-app-alaq/nom-assami.mp3",
"audios-app-alaq/nom-attawwab.mp3",
"audios-app-alaq/nom-malikalmulk.mp3",
"audios-app-alaq/noun-alif-son-prolonge.mp3",
"audios-app-alaq/noun-damma-son-court.mp3",
"audios-app-alaq/noun-fatha-son-court.mp3",
"audios-app-alaq/noun-isolee-nom-de-la-lettre.mp3",
"audios-app-alaq/noun-kasra-son-court.mp3",
"audios-app-alaq/noun-waw-son-prolonge.mp3",
"audios-app-alaq/noun-ya-son-prolonge.mp3",
"audios-app-alaq/qaf-alif-son-prolonge.mp3",
"audios-app-alaq/qaf-damma-son-court.mp3",
"audios-app-alaq/qaf-fatha-son-court.mp3",
"audios-app-alaq/qaf-kasra-son-court.mp3",
"audios-app-alaq/qaf-waw-son-prolonge.mp3",
"audios-app-alaq/qaf-ya-son-prolonge.mp3",
"audios-app-alaq/ra-alif-son-prolonge.mp3",
"audios-app-alaq/ra-damma-son-court.mp3",
"audios-app-alaq/ra-fatha-son-court.mp3",
"audios-app-alaq/ra-isolee-nom-de-la-lettre.mp3",
"audios-app-alaq/ra-kasra-son-court.mp3",
"audios-app-alaq/ra-waw-son-prolonge.mp3",
"audios-app-alaq/ra-ya-son-prolonge.mp3",
"audios-app-alaq/sad-alif-son-prolonge.mp3",
"audios-app-alaq/sad-damma-son-court.mp3",
"audios-app-alaq/sad-fatha-son-court.mp3",
"audios-app-alaq/sad-kasra-son-court.mp3",
"audios-app-alaq/sad-waw-son-prolonge.mp3",
"audios-app-alaq/sad-ya-son-prolonge.mp3",
"audios-app-alaq/sfx-bonne-reponse.mp3",
"audios-app-alaq/mim-fatha-son-court-f.mp3",
"audios-app-alaq/mim-kasra-son-court-f.mp3",
"audios-app-alaq/mim-damma-son-court-f.mp3",
"audios-app-alaq/mim-alif-son-prolonge-f.mp3",
"audios-app-alaq/mim-ya-son-prolonge-f.mp3",
"audios-app-alaq/mim-waw-son-prolonge-f.mp3",
"audios-app-alaq/mot-madrasatoun.mp3",
"audios-app-alaq/sin-alif-son-prolonge.mp3",
"audios-app-alaq/sin-damma-son-court.mp3",
"audios-app-alaq/sin-fatha-son-court.mp3",
"audios-app-alaq/sin-kasra-son-court.mp3",
"audios-app-alaq/sin-waw-son-prolonge.mp3",
"audios-app-alaq/sin-ya-son-prolonge.mp3",
"audios-app-alaq/ta-alif-son-prolonge.mp3",
"audios-app-alaq/ta-damma-son-court.mp3",
"audios-app-alaq/ta-fatha-son-court.mp3",
"audios-app-alaq/ta-kasra-son-court.mp3",
"audios-app-alaq/ta-waw-son-prolonge.mp3",
"audios-app-alaq/ta-ya-son-prolonge.mp3",
"audios-app-alaq/tta-alif-son-prolonge.mp3",
"audios-app-alaq/tta-damma-son-court.mp3",
"audios-app-alaq/tta-fatha-son-court.mp3",
"audios-app-alaq/tta-kasra-son-court.mp3",
"audios-app-alaq/tta-waw-son-prolonge.mp3",
"audios-app-alaq/tta-ya-son-prolonge.mp3",
"audios-app-alaq/voyelle-a.mp3",
"audios-app-alaq/voyelle-i.mp3",
"audios-app-alaq/voyelle-ou.mp3",
"audios-app-alaq/waw-alif-son-prolonge.mp3",
"audios-app-alaq/waw-damma-son-court.mp3",
"audios-app-alaq/waw-fatha-son-court.mp3",
"audios-app-alaq/waw-isolee-nom-de-la-lettre.mp3",
"audios-app-alaq/waw-kasra-son-court.mp3",
"audios-app-alaq/waw-waw-son-prolonge.mp3",
"audios-app-alaq/waw-ya-son-prolonge.mp3",
"audios-app-alaq/ya-alif-son-prolonge.mp3",
"audios-app-alaq/ya-damma-son-court.mp3",
"audios-app-alaq/ya-fatha-son-court.mp3",
"audios-app-alaq/ya-isolee-nom-de-la-lettre.mp3",
"audios-app-alaq/ya-kasra-son-court.mp3",
"audios-app-alaq/ya-waw-son-prolonge.mp3",
"audios-app-alaq/ya-ya-son-prolonge.mp3"
];

self.addEventListener('install',e=>{
  e.waitUntil((async()=>{
    const c=await caches.open(CACHE);
    await c.addAll(CORE);   // le cœur SEULEMENT : l'installation doit être rapide
    self.skipWaiting();
  })());
});
/* Les 301 audios + les icônes sont pré-chargés APRÈS le premier rendu : la page envoie
   « precache » quand elle est affichée. Avant, ils saturaient le réseau pendant le chargement
   (écran blanc à chaque déploiement). */
let _preFait=false;
/* Six téléchargements à la fois, pas 360. Lancer toute la liste d'un coup ne la rendait
   pas plus rapide — le navigateur la met de toute façon en file — mais cette file entrait
   en concurrence avec ce dont l'app a besoin au même instant : Supabase, les polices, et
   désormais la récitation streamée. Et l'on SAUTE ce qui est déjà là : au deuxième
   passage, c'est 360 lectures de cache, zéro requête réseau. */
async function enFile(liste,c,n){
  let i=0;
  const ouvrier=async()=>{
    while(i<liste.length){
      const u=liste[i++];
      try{ if(await c.match(u))continue; await c.add(u); }catch(_){ } // un 404 ne doit rien casser
    }
  };
  await Promise.all(Array.from({length:n},ouvrier));
}
async function precacheLourd(){
  if(_preFait)return; _preFait=true;
  const c=await caches.open(MEDIA);
  await enFile(IMAGES.concat(AUDIOS),c,6);
}
self.addEventListener('message',e=>{ if(e.data==='precache')e.waitUntil(precacheLourd()); });
self.addEventListener('activate',e=>{
  e.waitUntil((async()=>{
    const keys=await caches.keys();
    // MEDIA survit aux livraisons : c'est tout l'objet de la séparation
    await Promise.all(keys.filter(k=>k!==CACHE&&k!==MEDIA).map(k=>caches.delete(k)));
    // ⚠️ MEDIA n'est jamais purgé — donc un fichier REMPLACÉ sous le même nom y reste
    // périmé pour toujours. Purge CIBLÉE des remplacés du 07/08 (alif « alfoun », fā
    // emphatique, madrasatoun) : ils se re-téléchargent une fois, puis re-cache à vie.
    const m=await caches.open(MEDIA);
    await Promise.all(['lettre-alif-nom-f.mp3','lettre-alif-nom-h.mp3',
      'lettre-fa-nom-f.mp3','lettre-fa-nom-h.mp3','mot-madrasatoun.mp3']
      .map(f=>m.delete('audios-app-alaq/'+f,{ignoreSearch:true})));
    self.clients.claim();
  })());
});
self.addEventListener('fetch',e=>{
  const url=new URL(e.request.url);
  // navigation / index : réseau d'abord, cache en secours
  if(e.request.mode==='navigate'||url.pathname.endsWith('/index.html')||url.pathname==='/'){
    e.respondWith((async()=>{
      const c=await caches.open(CACHE);
      const hit=await c.match('index.html');
      // rafraîchissement SILENCIEUX en arrière-plan : la prochaine ouverture aura la nouvelle version
      const frais=fetch(e.request).then(r=>{c.put('index.html',r.clone());return r;}).catch(()=>null);
      // le cache d'abord : l'app s'ouvre TOUT DE SUITE, même si le réseau traîne
      return hit || (await frais) || (await caches.match('.')) || Response.error();
    })());
    return;
  }
  // audios, polices Google, récitation, icônes : cache d'abord
  const cacheFirst=url.pathname.indexOf('/audios-app-alaq/')>=0
    ||url.hostname==='fonts.googleapis.com'||url.hostname==='fonts.gstatic.com'||url.hostname==='cdn.jsdelivr.net'
    ||url.hostname==='cdn.islamic.network'  // la récitation streamée : mise en cache côté client, comme leurs conditions le demandent
    ||/\.(png|jpe?g|mp3|mp4|woff2?)$/.test(url.pathname);
  if(cacheFirst){
    e.respondWith((async()=>{
      const hit=await caches.match(e.request);
      if(hit)return hit;
      try{
        const r=await fetch(e.request);
        // sons, polices, icônes, récitation : tout ça va dans MEDIA, jamais dans le cache versionné
        if(r&&(r.ok||r.type==='opaque')){const c=await caches.open(MEDIA);c.put(e.request,r.clone());}
        return r;
      }catch(_){return Response.error();}
    })());
  }
});
