/* sw.js — le service worker d'Alaq : hors ligne complet.
   · index.html et navigation : cache versionné d'abord, réseau si le cache est vide. Une
     livraison arrive par le NOUVEAU sw (skipWaiting), jamais en réécrivant l'ancien cache.
   · le cœur (la liste CORE) : cache versionné d'abord, réseau en secours.
   · audios, polices, icônes : cache d'abord ; audios et icônes pré-chargés après le 1er rendu.
   · la récitation est streamée (cdn.islamic.network) et mise en cache au fil de l'écoute.
   Gardes : outils/verifier-sw-horsligne.mjs (le sw joué dans un bac, réseau coupé).
   ⚠️ Vite, precache-sons, precache-u8 et installer-prises relisent ce fichier par son texte :
   en commentaire, jamais u8/u8.js entre apostrophes, ni un nom de son entre guillemets
   doubles, ni de crochet fermant suivi d'un point-virgule dans l'en-tête d'AUDIOS.
   (journal : sw.js · en-tête historique) */
const CACHE='alaq-v225-2026-09-19';  // L'APP : versionné, purgé à chaque livraison
/* MEDIA : cache à part, jamais purgé — un mp3 ne change pas de contenu, on ne le
   retélécharge pas à chaque livraison. */
const MEDIA='alaq-medias';
/* IMGCACHE : versionné à part. ⚠️ Une image retouchée garde souvent son nom et reste en
   cache à vie : incrémenter IMGV, et activate jette l'ancien cache d'images.
   (journal : sw.js · images retouchées trois fois sous le même nom) */
const IMGV=17;
const IMGCACHE='alaq-images-v'+IMGV;
/* LE BUNDLE supabase-js, PRÉ-CACHÉ. Sans lui SB reste nul : ni connexion ni synchro. Il était rangé
   dans MEDIA au premier passage RÉUSSI au réseau seulement — donc le premier démarrage HORS LIGNE
   après une livraison qui change son URL n'avait aucun client.
   ⛔ EXACTEMENT l'URL de la balise d'index.html : elle porte integrity, et une autre URL = un autre
   fichier (garde : verifier-sw-horsligne.mjs, qui la DÉRIVE de la balise).
   ⛔ Hors de CORE : addAll est atomique, le CDN ferait échouer toute l'installation.
   (journal : sw.js · le bundle supabase pré-caché) */
const SUPABASE_JS='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.116.0/dist/umd/supabase.js';
const CORE=['.','index.html','u8/u8.js','u8/u8.css','app.css','squelette.js','assets.js','trace-lettres.js','donnees.js','generateurs.js','son.js','progression.js','parcours.js','ui/accueil.js','ui/navigation.js','ui/parametres.js','ui/reviser.js','revision.js','signalements.js','constance.js','comptes.js','bulles-tutoriels.js','coque.js','rail-ordinateur.js','ciel-v1.js','ciel-v2.js','content/unites.js','confidentialite.html','polices/polices.css','manifest.webmanifest','icon-192.png','icon-512.png','apple-touch-icon.png'];
/* Chemins du cœur résolus contre l'URL du sw (racine en prod, sous-dossier en local), dérivés
   à l'exécution : ce que le build ajoute à CORE (le paquet u8) y entre tout seul. */
const COEUR=new Set(CORE.filter(u=>u!=='.'&&u!=='index.html').map(u=>new URL(u,self.location.href).pathname));
const RACINE_SW=new URL('.',self.location.href).pathname;   // '/' en prod, '/dist/' ou '/alaq-vercel-static/' en local
const IMAGES=[ // icônes des disques de l'accueil — sans elles les disques sont vides
"images-app-alaq/icone-tb-lanterne-v1.png",
"images-app-alaq/icone-porte-v1.png",
"images-app-alaq/icone-main-glisse-v2.png",
"images-app-alaq/icone-ciel-dromadaire-v1.png",
"images-app-alaq/icone-tb-epi-v1.png",
"images-app-alaq/epi-pousse-anime-v1.webp",
"images-app-alaq/icone-tb-coeur-v1.png",
"images-app-alaq/icone-loupe-v1.png",
"images-app-alaq/icone-loupe-v1-clair.png",  // jumeau du mode clair : sans lui, loupe morte hors ligne
"images-app-alaq/icone-tab-video.png",
"images-app-alaq/icone-tab-cartes.png",
"images-app-alaq/icone-tab-crayon.png",
"images-app-alaq/icone-tab-parchemin.png",
"images-app-alaq/icone-tab-puzzle.png",
"images-app-alaq/icone-tab-micro.png",
"images-app-alaq/icone-tab-etoiles.png",
"images-app-alaq/icone-tab2-lire.png",
"images-app-alaq/icone-tab2-qoran.png",
"images-app-alaq/icone-tab2-ecrire.png",
"badges/disque1.png",
"badges/unite1.png",
"badges/sourate1.png",
"badges/sansfaute.png",
"badges/unite-sansfaute.png",
"badges/ecusson-vierge.png",
"badges/lecons1.png",
"badges/lecons2.png",
"badges/lecons3.png",
"badges/lecons10.png",
"badges/lecons20.png",
"badges/lecons50.png",
"badges/lecons100.png",
"badges/lecons200.png",
"badges/lecons500.png",
"badges/lecons1000.png",
"badges/serie3.png",
"badges/serie7.png",
"badges/serie30.png",
"badges/serie120.png",
"badges/serie360.png",
"badges/revision.png",
"badges/revision3.png",
"badges/revision7.png",
"badges/revision30.png",
"badges/revision50.png",
"badges/revision120.png",
"badges/revision360.png",
"images-app-alaq/icone-prm-sons.png",
"images-app-alaq/icone-prm-objectif.png",
"images-app-alaq/icone-prm-apropos.png",
"images-app-alaq/icone-prm-voix.png",
"images-app-alaq/icone-ecran-corriger.png",
"images-app-alaq/icone-ecran-ghufran.png",
"images-app-alaq/icone-ecran-pousse.png",
"images-app-alaq/icone-ecran-compte.png",
"images-app-alaq/icone-menu-apprendre.png",
"images-app-alaq/icone-menu-cours.png",
"images-app-alaq/icone-menu-reviser.png",
"images-app-alaq/icone-menu-profil.png",
"images-app-alaq/icone-menu-parametres.png",
"images-app-alaq/icone-disq8-a-bilan.png",
"images-app-alaq/icone-disq7-c-bilan.png",
"images-app-alaq/icone-disq8-a-decouvrir.png",
"images-app-alaq/icone-disq7-c-decouvrir.png",
"images-app-alaq/icone-disq8-a-ecrire.png",
"images-app-alaq/icone-disq7-c-ecrire.png",
"images-app-alaq/icone-disq8-a-lire.png",
"images-app-alaq/icone-disq7-c-lire.png",
"images-app-alaq/icone-disq8-a-memoriser.png",
"images-app-alaq/icone-disq7-c-memoriser.png",
"images-app-alaq/icone-disq8-a-qoran.png",
"images-app-alaq/icone-disq7-c-qoran.png",
"images-app-alaq/icone-disq8-a-reviser.png",
"images-app-alaq/icone-disq7-c-reviser.png"
];
const AUDIOS=[
/* ⛔ Liste dérivée de la table du son : node outils/precache-sons.mjs --ecrire la régénère,
   outils/verifier-son.mjs rougit s'il manque un son. Ne pas l'éditer à la main.
   (journal : sw.js · la liste AUDIOS) */
"audios-app-alaq/ain-alif-son-prolonge.mp3",
"audios-app-alaq/ain-damma-son-court.mp3",
"audios-app-alaq/ain-fatha-son-court.mp3",
"audios-app-alaq/ain-kasra-son-court.mp3",
"audios-app-alaq/ain-waw-son-prolonge.mp3",
"audios-app-alaq/ain-ya-son-prolonge.mp3",
"audios-app-alaq/al-chedda.mp3",
"audios-app-alaq/al-soukoun.mp3",
"audios-app-alaq/al-tanwin.mp3",
"audios-app-alaq/alif-alif-son-prolonge.mp3",
"audios-app-alaq/alif-damma-son-court.mp3",
"audios-app-alaq/alif-fatha-son-court.mp3",
"audios-app-alaq/alif-kasra-son-court.mp3",
"audios-app-alaq/alif-waw-son-prolonge.mp3",
"audios-app-alaq/alif-ya-son-prolonge.mp3",
"audios-app-alaq/am-chedda.mp3",
"audios-app-alaq/am-soukoun.mp3",
"audios-app-alaq/am-tanwin.mp3",
"audios-app-alaq/an-chedda.mp3",
"audios-app-alaq/an-soukoun.mp3",
"audios-app-alaq/an-tanwin.mp3",
"audios-app-alaq/ba-alif-son-prolonge.mp3",
"audios-app-alaq/ba-damma-son-court.mp3",
"audios-app-alaq/ba-fatha-son-court.mp3",
"audios-app-alaq/ba-kasra-son-court.mp3",
"audios-app-alaq/ba-waw-son-prolonge.mp3",
"audios-app-alaq/ba-ya-son-prolonge.mp3",
"audios-app-alaq/dad-alif-son-prolonge.mp3",
"audios-app-alaq/dad-damma-son-court.mp3",
"audios-app-alaq/dad-fatha-son-court.mp3",
"audios-app-alaq/dad-kasra-son-court.mp3",
"audios-app-alaq/dad-waw-son-prolonge.mp3",
"audios-app-alaq/dad-ya-son-prolonge.mp3",
"audios-app-alaq/dal-alif-son-prolonge.mp3",
"audios-app-alaq/dal-damma-son-court.mp3",
"audios-app-alaq/dal-fatha-son-court.mp3",
"audios-app-alaq/dal-kasra-son-court.mp3",
"audios-app-alaq/dal-waw-son-prolonge.mp3",
"audios-app-alaq/dal-ya-son-prolonge.mp3",
"audios-app-alaq/dhal-alif-son-prolonge.mp3",
"audios-app-alaq/dhal-damma-son-court.mp3",
"audios-app-alaq/dhal-fatha-son-court.mp3",
"audios-app-alaq/dhal-kasra-son-court.mp3",
"audios-app-alaq/dhal-waw-son-prolonge.mp3",
"audios-app-alaq/dhal-ya-son-prolonge.mp3",
"audios-app-alaq/faux-albayt.mp3",
"audios-app-alaq/faux-aldalw.mp3",
"audios-app-alaq/faux-aldhahab.mp3",
"audios-app-alaq/faux-alhimar.mp3",
"audios-app-alaq/faux-alqamar.mp3",
"audios-app-alaq/faux-alrumman.mp3",
"audios-app-alaq/faux-alyad.mp3",
"audios-app-alaq/felicit-allahumma-barik-f.mp3",
"audios-app-alaq/felicit-moumtaz-f.mp3",
"audios-app-alaq/felicit-rai-f.mp3",
"audios-app-alaq/felicit-sahih-f.mp3",
"audios-app-alaq/ghayn-alif-son-prolonge.mp3",
"audios-app-alaq/ghayn-damma-son-court.mp3",
"audios-app-alaq/ghayn-fatha-son-court.mp3",
"audios-app-alaq/ghayn-kasra-son-court.mp3",
"audios-app-alaq/ghayn-waw-son-prolonge.mp3",
"audios-app-alaq/ghayn-ya-son-prolonge.mp3",
"audios-app-alaq/ha-alif-son-prolonge.mp3",
"audios-app-alaq/ha-damma-son-court.mp3",
"audios-app-alaq/ha-fatha-son-court.mp3",
"audios-app-alaq/ha-kasra-son-court.mp3",
"audios-app-alaq/ha-waw-son-prolonge.mp3",
"audios-app-alaq/ha-ya-son-prolonge.mp3",
"audios-app-alaq/hha-alif-son-prolonge.mp3",
"audios-app-alaq/hha-damma-son-court.mp3",
"audios-app-alaq/hha-fatha-son-court.mp3",
"audios-app-alaq/hha-kasra-son-court.mp3",
"audios-app-alaq/hha-waw-son-prolonge.mp3",
"audios-app-alaq/hha-ya-son-prolonge.mp3",
"audios-app-alaq/kaf-alif-son-prolonge.mp3",
"audios-app-alaq/kaf-damma-son-court.mp3",
"audios-app-alaq/kaf-fatha-son-court.mp3",
"audios-app-alaq/kaf-kasra-son-court.mp3",
"audios-app-alaq/kaf-waw-son-prolonge.mp3",
"audios-app-alaq/kaf-ya-son-prolonge.mp3",
"audios-app-alaq/lam-alif-son-prolonge.mp3",
"audios-app-alaq/lam-damma-son-court.mp3",
"audios-app-alaq/lam-fatha-son-court.mp3",
"audios-app-alaq/lam-kasra-son-court.mp3",
"audios-app-alaq/lam-waw-son-prolonge.mp3",
"audios-app-alaq/lam-ya-son-prolonge.mp3",
"audios-app-alaq/lettre-alif-nom.mp3",
"audios-app-alaq/lettre-ayn-nom.mp3",
"audios-app-alaq/lettre-ayn-son.mp3",
"audios-app-alaq/lettre-ba-nom.mp3",
"audios-app-alaq/lettre-ba-son.mp3",
"audios-app-alaq/lettre-dad-nom.mp3",
"audios-app-alaq/lettre-dad-son.mp3",
"audios-app-alaq/lettre-dal-nom.mp3",
"audios-app-alaq/lettre-dal-son.mp3",
"audios-app-alaq/lettre-dha-nom.mp3",
"audios-app-alaq/lettre-dha-son.mp3",
"audios-app-alaq/lettre-dhal-nom.mp3",
"audios-app-alaq/lettre-dhal-son.mp3",
"audios-app-alaq/lettre-fa-nom.mp3",
"audios-app-alaq/lettre-fa-son.mp3",
"audios-app-alaq/lettre-ghayn-nom.mp3",
"audios-app-alaq/lettre-ghayn-son.mp3",
"audios-app-alaq/lettre-ha-nom.mp3",
"audios-app-alaq/lettre-ha-son.mp3",
"audios-app-alaq/lettre-hamza-nom.mp3",
"audios-app-alaq/lettre-hha-nom.mp3",
"audios-app-alaq/lettre-hha-son.mp3",
"audios-app-alaq/lettre-jim-nom.mp3",
"audios-app-alaq/lettre-jim-son.mp3",
"audios-app-alaq/lettre-kaf-nom.mp3",
"audios-app-alaq/lettre-kaf-son.mp3",
"audios-app-alaq/lettre-kha-nom.mp3",
"audios-app-alaq/lettre-kha-son.mp3",
"audios-app-alaq/lettre-lam-nom.mp3",
"audios-app-alaq/lettre-lam-son.mp3",
"audios-app-alaq/lettre-mim-nom.mp3",
"audios-app-alaq/lettre-mim-son.mp3",
"audios-app-alaq/lettre-nun-nom.mp3",
"audios-app-alaq/lettre-nun-son.mp3",
"audios-app-alaq/lettre-qaf-nom.mp3",
"audios-app-alaq/lettre-qaf-son.mp3",
"audios-app-alaq/lettre-ra-nom.mp3",
"audios-app-alaq/lettre-ra-son.mp3",
"audios-app-alaq/lettre-sad-nom.mp3",
"audios-app-alaq/lettre-sad-son.mp3",
"audios-app-alaq/lettre-shin-nom.mp3",
"audios-app-alaq/lettre-shin-son.mp3",
"audios-app-alaq/lettre-sin-nom.mp3",
"audios-app-alaq/lettre-sin-son.mp3",
"audios-app-alaq/lettre-ta-nom.mp3",
"audios-app-alaq/lettre-ta-son.mp3",
"audios-app-alaq/lettre-tha-nom.mp3",
"audios-app-alaq/lettre-tha-son.mp3",
"audios-app-alaq/lettre-tta-nom.mp3",
"audios-app-alaq/lettre-tta-son.mp3",
"audios-app-alaq/lettre-waw-nom.mp3",
"audios-app-alaq/lettre-waw-son.mp3",
"audios-app-alaq/lettre-ya-nom.mp3",
"audios-app-alaq/lettre-ya-son.mp3",
"audios-app-alaq/lettre-zay-nom.mp3",
"audios-app-alaq/lettre-zay-son.mp3",
"audios-app-alaq/mim-alif-son-prolonge.mp3",
"audios-app-alaq/mim-damma-son-court.mp3",
"audios-app-alaq/mim-fatha-son-court.mp3",
"audios-app-alaq/mim-kasra-son-court.mp3",
"audios-app-alaq/mim-waw-son-prolonge.mp3",
"audios-app-alaq/mim-ya-son-prolonge.mp3",
"audios-app-alaq/mot-aalim.mp3",
"audios-app-alaq/mot-addallin.mp3",
"audios-app-alaq/mot-addalloun.mp3",
"audios-app-alaq/mot-addini.mp3",
"audios-app-alaq/mot-ahad.mp3",
"audios-app-alaq/mot-aktub.mp3",
"audios-app-alaq/mot-ala.mp3",
"audios-app-alaq/mot-alalbab.mp3",
"audios-app-alaq/mot-alalbayt.mp3",
"audios-app-alaq/mot-alalhimar.mp3",
"audios-app-alaq/mot-alalmaktab.mp3",
"audios-app-alaq/mot-alam.mp3",
"audios-app-alaq/mot-alamin.mp3",
"audios-app-alaq/mot-alamoun.mp3",
"audios-app-alaq/mot-alannabat.mp3",
"audios-app-alaq/mot-alayhim.mp3",
"audios-app-alaq/mot-albab.mp3",
"audios-app-alaq/mot-albayt.mp3",
"audios-app-alaq/mot-albint.mp3",
"audios-app-alaq/mot-aldalw.mp3",
"audios-app-alaq/mot-aldar.mp3",
"audios-app-alaq/mot-aldhahab.mp3",
"audios-app-alaq/mot-alhabl.mp3",
"audios-app-alaq/mot-alhamdu.mp3",
"audios-app-alaq/mot-alhamdulillah.mp3",
"audios-app-alaq/mot-alhimar.mp3",
"audios-app-alaq/mot-alim.mp3",
"audios-app-alaq/mot-alladhina.mp3",
"audios-app-alaq/mot-allah.mp3",
"audios-app-alaq/mot-almaa.mp3",
"audios-app-alaq/mot-almaghdoubou.mp3",
"audios-app-alaq/mot-almaghdub.mp3",
"audios-app-alaq/mot-almaktab.mp3",
"audios-app-alaq/mot-almustaqima.mp3",
"audios-app-alaq/mot-alnahl.mp3",
"audios-app-alaq/mot-alqalam.mp3",
"audios-app-alaq/mot-alqamar.mp3",
"audios-app-alaq/mot-alrumman.mp3",
"audios-app-alaq/mot-altayr.mp3",
"audios-app-alaq/mot-altin.mp3",
"audios-app-alaq/mot-alumm.mp3",
"audios-app-alaq/mot-alwalad.mp3",
"audios-app-alaq/mot-alyad.mp3",
"audios-app-alaq/mot-amal.mp3",
"audios-app-alaq/mot-aman.mp3",
"audios-app-alaq/mot-amin.mp3",
"audios-app-alaq/mot-amr.mp3",
"audios-app-alaq/mot-anamta.mp3",
"audios-app-alaq/mot-annabat.mp3",
"audios-app-alaq/mot-annas.mp3",
"audios-app-alaq/mot-arabi.mp3",
"audios-app-alaq/mot-arrahim.mp3",
"audios-app-alaq/mot-arrahimi.mp3",
"audios-app-alaq/mot-arrahman.mp3",
"audios-app-alaq/mot-arrahmani.mp3",
"audios-app-alaq/mot-assamad.mp3",
"audios-app-alaq/mot-assirata.mp3",
"audios-app-alaq/mot-attayralalbayt.mp3",
"audios-app-alaq/mot-atturab.mp3",
"audios-app-alaq/mot-audhu.mp3",
"audios-app-alaq/mot-ayn.mp3",
"audios-app-alaq/mot-bab.mp3",
"audios-app-alaq/mot-bayt.mp3",
"audios-app-alaq/mot-bi-ismin.mp3",
"audios-app-alaq/mot-bi.mp3",
"audios-app-alaq/mot-bilhabl.mp3",
"audios-app-alaq/mot-bilmaa.mp3",
"audios-app-alaq/mot-bilqalam.mp3",
"audios-app-alaq/mot-bilyad.mp3",
"audios-app-alaq/mot-bint.mp3",
"audios-app-alaq/mot-binttatasallaqbilhabl.mp3",
"audios-app-alaq/mot-bismi.mp3",
"audios-app-alaq/mot-bismillah.mp3",
"audios-app-alaq/mot-bitturab.mp3",
"audios-app-alaq/mot-dalw.mp3",
"audios-app-alaq/mot-dar.mp3",
"audios-app-alaq/mot-dars.mp3",
"audios-app-alaq/mot-dhahab.mp3",
"audios-app-alaq/mot-dhahaba.mp3",
"audios-app-alaq/mot-din.mp3",
"audios-app-alaq/mot-ghasiq.mp3",
"audios-app-alaq/mot-ghayb.mp3",
"audios-app-alaq/mot-ghayr.mp3",
"audios-app-alaq/mot-habl.mp3",
"audios-app-alaq/mot-hablalalmaktab.mp3",
"audios-app-alaq/mot-hablilhimar.mp3",
"audios-app-alaq/mot-hablul-bint.mp3",
"audios-app-alaq/mot-hablul-himar.mp3",
"audios-app-alaq/mot-hasid.mp3",
"audios-app-alaq/mot-hatab.mp3",
"audios-app-alaq/mot-himar.mp3",
"audios-app-alaq/mot-hum.mp3",
"audios-app-alaq/mot-huwa.mp3",
"audios-app-alaq/mot-idha.mp3",
"audios-app-alaq/mot-ihdina.mp3",
"audios-app-alaq/mot-ilah.mp3",
"audios-app-alaq/mot-ilayna.mp3",
"audios-app-alaq/mot-imam.mp3",
"audios-app-alaq/mot-iman.mp3",
"audios-app-alaq/mot-ismoun.mp3",
"audios-app-alaq/mot-iyyaka.mp3",
"audios-app-alaq/mot-karim.mp3",
"audios-app-alaq/mot-kasaba.mp3",
"audios-app-alaq/mot-laban.mp3",
"audios-app-alaq/mot-lamma.mp3",
"audios-app-alaq/mot-lawm.mp3",
"audios-app-alaq/mot-lawn.mp3",
"audios-app-alaq/mot-layl.mp3",
"audios-app-alaq/mot-li.mp3",
"audios-app-alaq/mot-lilbint.mp3",
"audios-app-alaq/mot-lilhimar.mp3",
"audios-app-alaq/mot-lillah.mp3",
"audios-app-alaq/mot-lilumm.mp3",
"audios-app-alaq/mot-lilwalad.mp3",
"audios-app-alaq/mot-lin.mp3",
"audios-app-alaq/mot-maalik.mp3",
"audios-app-alaq/mot-madrasatoun.mp3",
"audios-app-alaq/mot-maktab.mp3",
"audios-app-alaq/mot-mal.mp3",
"audios-app-alaq/mot-malik.mp3",
"audios-app-alaq/mot-mamnoun.mp3",
"audios-app-alaq/mot-manal.mp3",
"audios-app-alaq/mot-manam.mp3",
"audios-app-alaq/mot-mann.mp3",
"audios-app-alaq/mot-mustaqim.mp3",
"audios-app-alaq/mot-naabudu.mp3",
"audios-app-alaq/mot-nabat.mp3",
"audios-app-alaq/mot-nabi.mp3",
"audios-app-alaq/mot-nahl.mp3",
"audios-app-alaq/mot-nahlaalanabat.mp3",
"audios-app-alaq/mot-naml.mp3",
"audios-app-alaq/mot-nastain.mp3",
"audios-app-alaq/mot-nil.mp3",
"audios-app-alaq/mot-noun.mp3",
"audios-app-alaq/mot-oulama.mp3",
"audios-app-alaq/mot-qalam.mp3",
"audios-app-alaq/mot-qalamalalmaktab.mp3",
"audios-app-alaq/mot-qalamlilbint.mp3",
"audios-app-alaq/mot-qalamlilumm.mp3",
"audios-app-alaq/mot-qalamlilwalad.mp3",
"audios-app-alaq/mot-qalamul-bint.mp3",
"audios-app-alaq/mot-qalamul-walad.mp3",
"audios-app-alaq/mot-qamar.mp3",
"audios-app-alaq/mot-qul.mp3",
"audios-app-alaq/mot-rabb.mp3",
"audios-app-alaq/mot-rabi.mp3",
"audios-app-alaq/mot-rumman.mp3",
"audios-app-alaq/mot-rummanlilbint.mp3",
"audios-app-alaq/mot-rummanlilumm.mp3",
"audios-app-alaq/mot-rummanlilwalad.mp3",
"audios-app-alaq/mot-sabr.mp3",
"audios-app-alaq/mot-sirat.mp3",
"audios-app-alaq/mot-sudur.mp3",
"audios-app-alaq/mot-tabba.mp3",
"audios-app-alaq/mot-tariq.mp3",
"audios-app-alaq/mot-tayr.mp3",
"audios-app-alaq/mot-tayralalbayt.mp3",
"audios-app-alaq/mot-tayrul-bint.mp3",
"audios-app-alaq/mot-tayrul-walad.mp3",
"audios-app-alaq/mot-tin.mp3",
"audios-app-alaq/mot-tinlilhimar.mp3",
"audios-app-alaq/mot-tinlilumm.mp3",
"audios-app-alaq/mot-tinlilwalad.mp3",
"audios-app-alaq/mot-umm.mp3",
"audios-app-alaq/mot-umr.mp3",
"audios-app-alaq/mot-uqad.mp3",
"audios-app-alaq/mot-walad.mp3",
"audios-app-alaq/mot-waladyaktub.mp3",
"audios-app-alaq/mot-waladyaktubbilqalam.mp3",
"audios-app-alaq/mot-waladyatawadda.mp3",
"audios-app-alaq/mot-waladyatawaddabilmaa.mp3",
"audios-app-alaq/mot-waladyatayammam.mp3",
"audios-app-alaq/mot-waladyatayammambitturab.mp3",
"audios-app-alaq/mot-waqaba.mp3",
"audios-app-alaq/mot-yad.mp3",
"audios-app-alaq/mot-yamin.mp3",
"audios-app-alaq/mot-yawm.mp3",
"audios-app-alaq/nom-addarr.mp3",
"audios-app-alaq/nom-aladl.mp3",
"audios-app-alaq/nom-alalim.mp3",
"audios-app-alaq/nom-alaliyy.mp3",
"audios-app-alaq/nom-alawwal.mp3",
"audios-app-alaq/nom-albadi.mp3",
"audios-app-alaq/nom-albaqi.mp3",
"audios-app-alaq/nom-albari.mp3",
"audios-app-alaq/nom-albarr.mp3",
"audios-app-alaq/nom-albasir.mp3",
"audios-app-alaq/nom-albasit.mp3",
"audios-app-alaq/nom-albatin.mp3",
"audios-app-alaq/nom-alghaniyy.mp3",
"audios-app-alaq/nom-alhadi.mp3",
"audios-app-alaq/nom-alhakam.mp3",
"audios-app-alaq/nom-alhakim.mp3",
"audios-app-alaq/nom-alhalim.mp3",
"audios-app-alaq/nom-alhamid.mp3",
"audios-app-alaq/nom-alhaqq.mp3",
"audios-app-alaq/nom-alhasib.mp3",
"audios-app-alaq/nom-alhayy.mp3",
"audios-app-alaq/nom-alkabir.mp3",
"audios-app-alaq/nom-alkarim.mp3",
"audios-app-alaq/nom-allah.mp3",
"audios-app-alaq/nom-almalik.mp3",
"audios-app-alaq/nom-almani.mp3",
"audios-app-alaq/nom-almatin.mp3",
"audios-app-alaq/nom-almubdi.mp3",
"audios-app-alaq/nom-almudhill.mp3",
"audios-app-alaq/nom-almughni.mp3",
"audios-app-alaq/nom-almuhaymin.mp3",
"audios-app-alaq/nom-almuhsi.mp3",
"audios-app-alaq/nom-almuhyi.mp3",
"audios-app-alaq/nom-almuid.mp3",
"audios-app-alaq/nom-almumin.mp3",
"audios-app-alaq/nom-almumit.mp3",
"audios-app-alaq/nom-almuntaqim.mp3",
"audios-app-alaq/nom-almuqaddim.mp3",
"audios-app-alaq/nom-almuqit.mp3",
"audios-app-alaq/nom-almuqsit.mp3",
"audios-app-alaq/nom-almuqtadir.mp3",
"audios-app-alaq/nom-almusawwir.mp3",
"audios-app-alaq/nom-almutaali.mp3",
"audios-app-alaq/nom-almutakabbir.mp3",
"audios-app-alaq/nom-alqabid.mp3",
"audios-app-alaq/nom-alqadir.mp3",
"audios-app-alaq/nom-alqahhar.mp3",
"audios-app-alaq/nom-alqawiyy.mp3",
"audios-app-alaq/nom-alqayyum.mp3",
"audios-app-alaq/nom-alquddus.mp3",
"audios-app-alaq/nom-alwadud.mp3",
"audios-app-alaq/nom-alwahhab.mp3",
"audios-app-alaq/nom-alwahid.mp3",
"audios-app-alaq/nom-alwakil.mp3",
"audios-app-alaq/nom-alwali.mp3",
"audios-app-alaq/nom-alwaliyy.mp3",
"audios-app-alaq/nom-alwasi.mp3",
"audios-app-alaq/nom-annur.mp3",
"audios-app-alaq/nom-arrahim.mp3",
"audios-app-alaq/nom-arrahman.mp3",
"audios-app-alaq/nom-arraqib.mp3",
"audios-app-alaq/nom-assabur.mp3",
"audios-app-alaq/nom-assalam.mp3",
"audios-app-alaq/nom-assamad.mp3",
"audios-app-alaq/nom-assami.mp3",
"audios-app-alaq/nom-attawwab.mp3",
"audios-app-alaq/nom-malikalmulk.mp3",
"audios-app-alaq/noun-alif-son-prolonge.mp3",
"audios-app-alaq/noun-damma-son-court.mp3",
"audios-app-alaq/noun-fatha-son-court.mp3",
"audios-app-alaq/noun-kasra-son-court.mp3",
"audios-app-alaq/noun-waw-son-prolonge.mp3",
"audios-app-alaq/noun-ya-son-prolonge.mp3",
"audios-app-alaq/qaf-alif-son-prolonge.mp3",
"audios-app-alaq/qaf-damma-son-court.mp3",
"audios-app-alaq/qaf-fatha-son-court.mp3",
"audios-app-alaq/qaf-kasra-son-court.mp3",
"audios-app-alaq/qaf-waw-son-prolonge.mp3",
"audios-app-alaq/qaf-ya-son-prolonge.mp3",
"audios-app-alaq/ra-alif-son-prolonge.mp3",
"audios-app-alaq/ra-damma-son-court.mp3",
"audios-app-alaq/ra-fatha-son-court.mp3",
"audios-app-alaq/ra-kasra-son-court.mp3",
"audios-app-alaq/ra-waw-son-prolonge.mp3",
"audios-app-alaq/ra-ya-son-prolonge.mp3",
"audios-app-alaq/sad-alif-son-prolonge.mp3",
"audios-app-alaq/sad-damma-son-court.mp3",
"audios-app-alaq/sad-fatha-son-court.mp3",
"audios-app-alaq/sad-kasra-son-court.mp3",
"audios-app-alaq/sad-waw-son-prolonge.mp3",
"audios-app-alaq/sad-ya-son-prolonge.mp3",
"audios-app-alaq/sfx-bonne-reponse.mp3",
"audios-app-alaq/sfx-erreur.mp3",
"audios-app-alaq/sfx-fin-lecon.mp3",
"audios-app-alaq/sin-alif-son-prolonge.mp3",
"audios-app-alaq/sin-damma-son-court.mp3",
"audios-app-alaq/sin-fatha-son-court.mp3",
"audios-app-alaq/sin-kasra-son-court.mp3",
"audios-app-alaq/sin-waw-son-prolonge.mp3",
"audios-app-alaq/sin-ya-son-prolonge.mp3",
"audios-app-alaq/ta-alif-son-prolonge.mp3",
"audios-app-alaq/ta-damma-son-court.mp3",
"audios-app-alaq/ta-fatha-son-court.mp3",
"audios-app-alaq/ta-kasra-son-court.mp3",
"audios-app-alaq/ta-waw-son-prolonge.mp3",
"audios-app-alaq/ta-ya-son-prolonge.mp3",
"audios-app-alaq/tta-alif-son-prolonge.mp3",
"audios-app-alaq/tta-damma-son-court.mp3",
"audios-app-alaq/tta-fatha-son-court.mp3",
"audios-app-alaq/tta-kasra-son-court.mp3",
"audios-app-alaq/tta-waw-son-prolonge.mp3",
"audios-app-alaq/tta-ya-son-prolonge.mp3",
"audios-app-alaq/voyelle-a.mp3",
"audios-app-alaq/voyelle-i.mp3",
"audios-app-alaq/voyelle-ou.mp3",
"audios-app-alaq/waw-alif-son-prolonge.mp3",
"audios-app-alaq/waw-damma-son-court.mp3",
"audios-app-alaq/waw-fatha-son-court.mp3",
"audios-app-alaq/waw-kasra-son-court.mp3",
"audios-app-alaq/waw-waw-son-prolonge.mp3",
"audios-app-alaq/waw-ya-son-prolonge.mp3",
"audios-app-alaq/ya-alif-son-prolonge.mp3",
"audios-app-alaq/ya-damma-son-court.mp3",
"audios-app-alaq/ya-fatha-son-court.mp3",
"audios-app-alaq/ya-kasra-son-court.mp3",
"audios-app-alaq/ya-waw-son-prolonge.mp3",
"audios-app-alaq/ya-ya-son-prolonge.mp3",];

/* Le bundle supabase-js dans MEDIA (jamais purgé : l'URL porte la version, le contenu est immuable).
   ⛔ Tout est avalé : jsDelivr injoignable ne doit JAMAIS faire échouer l'installation — l'app
   s'ouvrirait sans rien en avion. Deuxième chance après le premier rendu (precacheLourd).
   ⛔ mode 'cors' : la balise porte integrity+crossorigin, donc sa requête est cors ; une réponse
   OPAQUE lui serait refusée, et integrity ne peut pas vérifier une réponse opaque.
   ⚠️ Prix assumé : un CDN qui traîne retarde skipWaiting de 8 s au plus — l'ancien sw sert pendant
   ce temps, personne ne voit rien. */
async function pecherSupabase(){
  try{
    const c=await caches.open(MEDIA);
    if(await c.match(SUPABASE_JS))return;
    const stop=new AbortController(), t=setTimeout(()=>{try{stop.abort()}catch(_){}},8000);
    try{
      const r=await fetch(SUPABASE_JS,{mode:'cors',credentials:'omit',signal:stop.signal});
      if(r&&r.ok)await c.put(SUPABASE_JS,r);
    }finally{ clearTimeout(t); }
  }catch(_){ }
}
self.addEventListener('install',e=>{
  e.waitUntil((async()=>{
    const c=await caches.open(CACHE);
    await c.addAll(CORE);   // le cœur SEULEMENT : l'installation doit être rapide
    await pecherSupabase();
    self.skipWaiting();
  })());
});
/* Audios et icônes pré-chargés APRÈS le premier rendu (message « precache » de la page) :
   avant, ils saturaient le réseau pendant le chargement. */
let _preFait=false;
/* Six téléchargements à la fois, et ce qui est déjà en cache est sauté : la liste entière d'un
   coup concurrençait Supabase, les polices et la récitation. */
async function enFile(liste,c,n){
  let i=0;
  const ouvrier=async()=>{
    while(i<liste.length){
      const u=liste[i++];
      try{ if(await c.match(u))continue; await c.add(u); }catch(_){ } // un 404 ne doit rien casser
    }
  };
  await Promise.all(Array.from({length:n},ouvrier));
}
async function precacheLourd(){
  if(_preFait)return; _preFait=true;
  await pecherSupabase();   // deuxième chance si le CDN était injoignable à l'installation
  await enFile(IMAGES,await caches.open(IMGCACHE),6); // les images dans LEUR cache versionné
  await enFile(AUDIOS,await caches.open(MEDIA),6);
}
self.addEventListener('message',e=>{ if(e.data==='precache')e.waitUntil(precacheLourd()); });
self.addEventListener('activate',e=>{
  e.waitUntil((async()=>{
    const keys=await caches.keys();
    // MEDIA survit aux livraisons ; IMGCACHE survit tant qu'IMGV ne bouge pas
    await Promise.all(keys.filter(k=>k!==CACHE&&k!==MEDIA&&k!==IMGCACHE).map(k=>caches.delete(k)));
    // les images anciennement rangées dans MEDIA y restaient périmées : on les en sort
    try{
      const md=await caches.open(MEDIA);
      const ks=await md.keys();
      await Promise.all(ks.filter(rq=>/\.(png|jpe?g|webp|gif)$/.test(new URL(rq.url).pathname))
        .map(rq=>md.delete(rq)));
    }catch(_){ }
    // ⚠️ MEDIA n'est jamais purgé : un fichier remplacé sous le même nom DOIT rejoindre cette
    // liste (ou changer de nom), et CACHE monter pour la rejouer. Complétée par outils/installer-prises.js.
    // (journal : sw.js · la purge ciblée de MEDIA)
    const m=await caches.open(MEDIA);
    await Promise.all(['lettre-alif-nom-f.mp3','lettre-alif-nom-h.mp3',
      'lettre-fa-nom-f.mp3','lettre-fa-nom-h.mp3','mot-madrasatoun.mp3',
      'sfx-bonne-reponse.mp3','sfx-fin-lecon.mp3',
      /* 17/08 : noms de lettres en voix IA retirés */
      'lettre-ayn-nom-f.mp3','lettre-hamza-nom-f.mp3','lettre-lam-nom-f.mp3',
      'lettre-mim-nom-f.mp3','lettre-waw-nom-f.mp3',
      /* 10/08 : syllabes IA retirées et 4 mots à revoir */
      'lam-fatha-son-court-f.mp3',
      'lam-kasra-son-court-f.mp3',
      'lam-damma-son-court-f.mp3',
      'lam-alif-son-prolonge-f.mp3',
      'lam-ya-son-prolonge-f.mp3',
      'lam-waw-son-prolonge-f.mp3',
      'noun-fatha-son-court-f.mp3',
      'noun-kasra-son-court-f.mp3',
      'noun-damma-son-court-f.mp3',
      'noun-alif-son-prolonge-f.mp3',
      'noun-ya-son-prolonge-f.mp3',
      'noun-waw-son-prolonge-f.mp3',
      'ya-fatha-son-court-f.mp3',
      'ya-kasra-son-court-f.mp3',
      'ya-damma-son-court-f.mp3',
      'ya-alif-son-prolonge-f.mp3',
      'ya-ya-son-prolonge-f.mp3',
      'ya-waw-son-prolonge-f.mp3',
      'waw-fatha-son-court-f.mp3',
      'waw-kasra-son-court-f.mp3',
      'waw-damma-son-court-f.mp3',
      'waw-alif-son-prolonge-f.mp3',
      'waw-ya-son-prolonge-f.mp3',
      'waw-waw-son-prolonge-f.mp3',
      'ba-fatha-son-court-f.mp3',
      'ba-kasra-son-court-f.mp3',
      'ba-damma-son-court-f.mp3',
      'ba-alif-son-prolonge-f.mp3',
      'ba-ya-son-prolonge-f.mp3',
      'ba-waw-son-prolonge-f.mp3',
      'ra-fatha-son-court-f.mp3',
      'ra-kasra-son-court-f.mp3',
      'ra-damma-son-court-f.mp3',
      'ra-alif-son-prolonge-f.mp3',
      'ra-ya-son-prolonge-f.mp3',
      'ra-waw-son-prolonge-f.mp3',
      'ain-fatha-son-court-f.mp3',
      'ain-kasra-son-court-f.mp3',
      'ain-damma-son-court-f.mp3',
      'ain-alif-son-prolonge-f.mp3',
      'ain-ya-son-prolonge-f.mp3',
      'ain-waw-son-prolonge-f.mp3',
      'sin-fatha-son-court-f.mp3',
      'sin-kasra-son-court-f.mp3',
      'sin-damma-son-court-f.mp3',
      'sin-alif-son-prolonge-f.mp3',
      'sin-ya-son-prolonge-f.mp3',
      'sin-waw-son-prolonge-f.mp3',
      'dal-fatha-son-court-f.mp3',
      'dal-kasra-son-court-f.mp3',
      'dal-damma-son-court-f.mp3',
      'dal-alif-son-prolonge-f.mp3',
      'dal-ya-son-prolonge-f.mp3',
      'dal-waw-son-prolonge-f.mp3',
      'kaf-fatha-son-court-f.mp3',
      'kaf-kasra-son-court-f.mp3',
      'kaf-damma-son-court-f.mp3',
      'kaf-alif-son-prolonge-f.mp3',
      'kaf-ya-son-prolonge-f.mp3',
      'kaf-waw-son-prolonge-f.mp3',
      'hha-fatha-son-court-f.mp3',
      'hha-kasra-son-court-f.mp3',
      'hha-damma-son-court-f.mp3',
      'hha-alif-son-prolonge-f.mp3',
      'hha-ya-son-prolonge-f.mp3',
      'hha-waw-son-prolonge-f.mp3',
      'tta-fatha-son-court-f.mp3',
      'tta-kasra-son-court-f.mp3',
      'tta-damma-son-court-f.mp3',
      'tta-alif-son-prolonge-f.mp3',
      'tta-ya-son-prolonge-f.mp3',
      'tta-waw-son-prolonge-f.mp3',
      'qaf-fatha-son-court-f.mp3',
      'qaf-kasra-son-court-f.mp3',
      'qaf-damma-son-court-f.mp3',
      'qaf-alif-son-prolonge-f.mp3',
      'qaf-ya-son-prolonge-f.mp3',
      'qaf-waw-son-prolonge-f.mp3',
      'ta-fatha-son-court-f.mp3',
      'ta-kasra-son-court-f.mp3',
      'ta-damma-son-court-f.mp3',
      'ta-alif-son-prolonge-f.mp3',
      'ta-ya-son-prolonge-f.mp3',
      'ta-waw-son-prolonge-f.mp3',
      'sad-fatha-son-court-f.mp3',
      'sad-kasra-son-court-f.mp3',
      'sad-damma-son-court-f.mp3',
      'sad-alif-son-prolonge-f.mp3',
      'sad-ya-son-prolonge-f.mp3',
      'sad-waw-son-prolonge-f.mp3',
      'ghayn-fatha-son-court-f.mp3',
      'ghayn-kasra-son-court-f.mp3',
      'ghayn-damma-son-court-f.mp3',
      'ghayn-alif-son-prolonge-f.mp3',
      'ghayn-ya-son-prolonge-f.mp3',
      'ghayn-waw-son-prolonge-f.mp3',
      'ha-fatha-son-court-f.mp3',
      'ha-kasra-son-court-f.mp3',
      'ha-damma-son-court-f.mp3',
      'ha-alif-son-prolonge-f.mp3',
      'ha-ya-son-prolonge-f.mp3',
      'ha-waw-son-prolonge-f.mp3',
      'dhal-fatha-son-court-f.mp3',
      'dhal-kasra-son-court-f.mp3',
      'dhal-damma-son-court-f.mp3',
      'dhal-alif-son-prolonge-f.mp3',
      'dhal-ya-son-prolonge-f.mp3',
      'dhal-waw-son-prolonge-f.mp3',
      'dad-fatha-son-court-f.mp3',
      'dad-kasra-son-court-f.mp3',
      'dad-damma-son-court-f.mp3',
      'dad-alif-son-prolonge-f.mp3',
      'dad-ya-son-prolonge-f.mp3',
      'dad-waw-son-prolonge-f.mp3',
      'mot-kasaba-f.mp3',
      'mot-allah-f.mp3',
      'mot-alladhina-f.mp3',
      'mot-addallin-f.mp3',
      /* 15/08 : prises de Myriam */
      'dad-alif-son-prolonge.mp3',
      'dad-damma-son-court.mp3',
      'dad-fatha-son-court.mp3',
      'dad-kasra-son-court.mp3',
      'dad-waw-son-prolonge.mp3',
      'dad-ya-son-prolonge.mp3',
      'dhal-alif-son-prolonge.mp3',
      'dhal-damma-son-court.mp3',
      'dhal-fatha-son-court.mp3',
      'dhal-kasra-son-court.mp3',
      'dhal-waw-son-prolonge.mp3',
      'dhal-ya-son-prolonge.mp3',
      'ghayn-alif-son-prolonge.mp3',
      'ghayn-damma-son-court.mp3',
      'ghayn-fatha-son-court.mp3',
      'ghayn-kasra-son-court.mp3',
      'ghayn-waw-son-prolonge.mp3',
      'ghayn-ya-son-prolonge.mp3',
      'ha-alif-son-prolonge.mp3',
      'ha-damma-son-court.mp3',
      'ha-fatha-son-court.mp3',
      'ha-kasra-son-court.mp3',
      'ha-waw-son-prolonge.mp3',
      'ha-ya-son-prolonge.mp3',
      'hha-alif-son-prolonge.mp3',
      'hha-damma-son-court.mp3',
      'hha-fatha-son-court.mp3',
      'hha-kasra-son-court.mp3',
      'hha-waw-son-prolonge.mp3',
      'hha-ya-son-prolonge.mp3',
      'kaf-ya-son-prolonge.mp3',
      'lettre-dad-nom.mp3',
      'lettre-dad-nom-f.mp3',
      'lettre-dhal-nom.mp3',
      'lettre-dhal-nom-f.mp3',
      'lettre-ghayn-nom.mp3',
      'lettre-ghayn-nom-f.mp3',
      'lettre-ha-nom.mp3',
      'lettre-ha-nom-f.mp3',
      'lettre-hha-nom.mp3',
      'lettre-hha-nom-f.mp3',
      'lettre-qaf-nom.mp3',
      'lettre-qaf-nom-f.mp3',
      'lettre-sad-nom.mp3',
      'lettre-sad-nom-f.mp3',
      'lettre-ta-nom.mp3',
      'lettre-ta-nom-f.mp3',
      'lettre-tta-nom.mp3',
      'lettre-tta-nom-f.mp3',
      'mot-ahad.mp3',
      'mot-ahad-f.mp3',
      'mot-alayhim.mp3',
      'mot-alayhim-f.mp3',
      'mot-alhamdu.mp3',
      'mot-alhamdu-f.mp3',
      'mot-alladhina.mp3',
      'mot-allah.mp3',
      'mot-anamta.mp3',
      'mot-anamta-f.mp3',
      'mot-arrahim.mp3',
      'mot-arrahim-f.mp3',
      'mot-arrahman.mp3',
      'mot-arrahman-f.mp3',
      'mot-assamad.mp3',
      'mot-assamad-f.mp3',
      'mot-audhu.mp3',
      'mot-audhu-f.mp3',
      'mot-dhahaba.mp3',
      'mot-dhahaba-f.mp3',
      'mot-ghasiq.mp3',
      'mot-ghasiq-f.mp3',
      'mot-ghayb.mp3',
      'mot-ghayb-f.mp3',
      'mot-ghayr.mp3',
      'mot-ghayr-f.mp3',
      'mot-hasid.mp3',
      'mot-hasid-f.mp3',
      'mot-hatab.mp3',
      'mot-hatab-f.mp3',
      'mot-huwa.mp3',
      'mot-huwa-f.mp3',
      'mot-idha.mp3',
      'mot-idha-f.mp3',
      'mot-ihdina.mp3',
      'mot-ihdina-f.mp3',
      'mot-ilah.mp3',
      'mot-ilah-f.mp3',
      'mot-ilayna-f.mp3',
      'mot-imam-f.mp3',
      'mot-mustaqim.mp3',
      'mot-mustaqim-f.mp3',
      'mot-nastain.mp3',
      'mot-nastain-f.mp3',
      'mot-qul.mp3',
      'mot-qul-f.mp3',
      'mot-sabr.mp3',
      'mot-sabr-f.mp3',
      'mot-sirat.mp3',
      'mot-sirat-f.mp3',
      'mot-sudur.mp3',
      'mot-sudur-f.mp3',
      'mot-tabba.mp3',
      'mot-tabba-f.mp3',
      'mot-tariq.mp3',
      'mot-tariq-f.mp3',
      'mot-uqad.mp3',
      'mot-uqad-f.mp3',
      'mot-waqaba.mp3',
      'mot-waqaba-f.mp3',
      'nom-addarr.mp3',
      'nom-aladl.mp3',
      'nom-alalim.mp3',
      'nom-alaliyy.mp3',
      'nom-alawwal.mp3',
      'nom-albadi.mp3',
      'nom-albaqi.mp3',
      'nom-albari.mp3',
      'nom-albarr.mp3',
      'nom-albasir.mp3',
      'nom-albasit.mp3',
      'nom-albatin.mp3',
      'nom-alghaniyy.mp3',
      'nom-alhadi.mp3',
      'nom-alhakam.mp3',
      'nom-alhakim.mp3',
      'nom-alhalim.mp3',
      'nom-alhamid.mp3',
      'nom-alhaqq.mp3',
      'nom-alhasib.mp3',
      'nom-alhayy.mp3',
      'nom-alkabir.mp3',
      'nom-alkarim.mp3',
      'nom-allah.mp3',
      'nom-almalik.mp3',
      'nom-almani.mp3',
      'nom-almatin.mp3',
      'nom-almubdi.mp3',
      'nom-almudhill.mp3',
      'nom-almughni.mp3',
      'nom-almuhaymin.mp3',
      'nom-almuhsi.mp3',
      'nom-almuhyi.mp3',
      'nom-almuid.mp3',
      'nom-almumin.mp3',
      'nom-almumit.mp3',
      'nom-almuntaqim.mp3',
      'nom-almuqaddim.mp3',
      'nom-almuqit.mp3',
      'nom-almuqsit.mp3',
      'nom-almuqtadir.mp3',
      'nom-almusawwir.mp3',
      'nom-almutaali.mp3',
      'nom-almutakabbir.mp3',
      'nom-alqabid.mp3',
      'nom-alqadir.mp3',
      'nom-alqahhar.mp3',
      'nom-alqawiyy.mp3',
      'nom-alqayyum.mp3',
      'nom-alquddus.mp3',
      'nom-alwadud.mp3',
      'nom-alwahhab.mp3',
      'nom-alwahid.mp3',
      'nom-alwakil.mp3',
      'nom-alwali.mp3',
      'nom-alwaliyy.mp3',
      'nom-alwasi.mp3',
      'nom-annur.mp3',
      'nom-arrahim.mp3',
      'nom-arrahman.mp3',
      'nom-arraqib.mp3',
      'nom-assabur.mp3',
      'nom-assalam.mp3',
      'nom-assamad.mp3',
      'nom-assami.mp3',
      'nom-attawwab.mp3',
      'nom-malikalmulk.mp3',
      'qaf-alif-son-prolonge.mp3',
      'qaf-damma-son-court.mp3',
      'qaf-fatha-son-court.mp3',
      'qaf-kasra-son-court.mp3',
      'qaf-waw-son-prolonge.mp3',
      'qaf-ya-son-prolonge.mp3',
      'sad-alif-son-prolonge.mp3',
      'sad-damma-son-court.mp3',
      'sad-fatha-son-court.mp3',
      'sad-kasra-son-court.mp3',
      'sad-waw-son-prolonge.mp3',
      'sad-ya-son-prolonge.mp3',
      'sin-alif-son-prolonge.mp3',
      'sin-waw-son-prolonge.mp3',
      'sin-ya-son-prolonge.mp3',
      'ta-alif-son-prolonge.mp3',
      'ta-damma-son-court.mp3',
      'ta-fatha-son-court.mp3',
      'ta-kasra-son-court.mp3',
      'ta-waw-son-prolonge.mp3',
      'ta-ya-son-prolonge.mp3',
      'tta-alif-son-prolonge.mp3',
      'tta-damma-son-court.mp3',
      'tta-fatha-son-court.mp3',
      'tta-kasra-son-court.mp3',
      'tta-waw-son-prolonge.mp3',
      'tta-ya-son-prolonge.mp3',
      'voyelle-a.mp3',
      'voyelle-i.mp3',
      'voyelle-ou.mp3',
      /* 16/08 : prises de Myriam */
      'dal-alif-son-prolonge.mp3',
      'dal-damma-son-court.mp3',
      'dal-fatha-son-court.mp3',
      'dal-kasra-son-court.mp3',
      'dal-waw-son-prolonge.mp3',
      'dal-ya-son-prolonge.mp3',
      'kaf-alif-son-prolonge.mp3',
      'kaf-damma-son-court.mp3',
      'kaf-fatha-son-court.mp3',
      'kaf-kasra-son-court.mp3',
      'kaf-waw-son-prolonge.mp3',
      'lettre-dal-nom.mp3',
      'lettre-dal-nom-f.mp3',
      'lettre-dha-nom.mp3',
      'lettre-dha-nom-f.mp3',
      'lettre-fa-nom.mp3',
      'lettre-jim-nom.mp3',
      'lettre-jim-nom-f.mp3',
      'lettre-kaf-nom.mp3',
      'lettre-kaf-nom-f.mp3',
      'lettre-kha-nom.mp3',
      'lettre-kha-nom-f.mp3',
      'lettre-shin-nom.mp3',
      'lettre-shin-nom-f.mp3',
      'lettre-sin-nom.mp3',
      'lettre-sin-nom-f.mp3',
      'lettre-tha-nom.mp3',
      'lettre-tha-nom-f.mp3',
      'lettre-zay-nom.mp3',
      'lettre-zay-nom-f.mp3',
      'mot-albab-f.mp3',
      'mot-albayt-f.mp3',
      'mot-aldalw-f.mp3',
      'mot-aldar-f.mp3',
      'mot-aldhahab-f.mp3',
      'mot-alhabl-f.mp3',
      'mot-alhimar-f.mp3',
      'mot-alnahl-f.mp3',
      'mot-alqalam-f.mp3',
      'mot-alqamar-f.mp3',
      'mot-alrumman-f.mp3',
      'mot-altayr-f.mp3',
      'mot-altin-f.mp3',
      'mot-alyad-f.mp3',
      'mot-annas.mp3',
      'mot-annas-f.mp3',
      'mot-bayt-f.mp3',
      'mot-bismi.mp3',
      'mot-bismi-f.mp3',
      'mot-dalw-f.mp3',
      'mot-dar-f.mp3',
      'mot-dars.mp3',
      'mot-dars-f.mp3',
      'mot-dhahab-f.mp3',
      'mot-din.mp3',
      'mot-din-f.mp3',
      'mot-habl-f.mp3',
      'mot-himar-f.mp3',
      'mot-iyyaka.mp3',
      'mot-iyyaka-f.mp3',
      'mot-karim.mp3',
      'mot-karim-f.mp3',
      'mot-kasaba.mp3',
      'mot-maalik.mp3',
      'mot-maalik-f.mp3',
      'mot-malik.mp3',
      'mot-malik-f.mp3',
      'mot-naabudu.mp3',
      'mot-naabudu-f.mp3',
      'mot-nahl-f.mp3',
      'mot-qalam-f.mp3',
      'mot-qamar-f.mp3',
      'mot-rumman-f.mp3',
      'mot-tayr-f.mp3',
      'mot-tin-f.mp3',
      'mot-yad-f.mp3',
      'sin-damma-son-court.mp3',
      'sin-fatha-son-court.mp3',
      'sin-kasra-son-court.mp3',
      /* 16/08 : prises de Myriam */
      'lettre-ba-nom.mp3',
      'lettre-ba-nom-f.mp3',
      'lettre-nun-nom.mp3',
      'lettre-nun-nom-f.mp3',
      'lettre-ra-nom.mp3',
      'lettre-ra-nom-f.mp3',
      'lettre-ya-nom.mp3',
      'lettre-ya-nom-f.mp3',
      'mot-addallin.mp3',
      'mot-almaghdub.mp3',
      'mot-almaghdub-f.mp3',
      'mot-alrumman.mp3',
      'mot-bab.mp3',
      'mot-bab-f.mp3',
      /* 01/09 : mot-bi recoupé sous le même nom (journal : sw.js · mot-bi.mp3 recoupé) */
      'mot-bi.mp3',
    ]
      .map(f=>m.delete('audios-app-alaq/'+f,{ignoreSearch:true})));
    /* les 4 mp4 de l'écriture guidée U9, réécrits sous le même nom (journal : sw.js · les 4 mp4) */
    await Promise.all(['ecrire-sombre-bg.mp4','ecrire-clair-bg.mp4',
      'ecrire-sombre-panel.mp4','ecrire-clair-panel.mp4']
      .map(f=>m.delete('images-app-alaq/u9/'+f,{ignoreSearch:true})));
    self.clients.claim();
  })());
});
self.addEventListener('fetch',e=>{
  /* ⛔ Ne jamais intercepter une requête Range : Safari streame l'audio par tranches et exige
     un 206 ; un 200 complet venu du cache est refusé. (journal : sw.js · les requêtes Range) */
  if(e.request.headers.get('range'))return;
  const url=new URL(e.request.url);
  /* Navigation / index : cache versionné d'abord, réseau si vide. Seules la racine et
     index.html sont « l'index » ; une autre navigation hors CORE reçoit index.html mais rien
     n'est écrit. ⛔ Ne jamais réécrire l'ancien cache (index.html neuf + app.css ancien) : on
     n'écrit qu'en cas de trou. (journal : sw.js · la navigation et l'ancien cache réécrit) */
  const versIndex=url.pathname===RACINE_SW||url.pathname.endsWith('/index.html');
  if(versIndex||(e.request.mode==='navigate'&&!COEUR.has(url.pathname))){
    e.respondWith((async()=>{
      const c=await caches.open(CACHE);
      const hit=await c.match('index.html');
      if(hit)return hit;   // le cache d'abord : l'app s'ouvre TOUT DE SUITE, même si le réseau traîne
      try{
        const r=await fetch(e.request);
        if(r&&r.ok&&versIndex)c.put('index.html',r.clone());   // jamais un 500 ni un portail captif, jamais une autre page
        return r;
      }catch(_){return (await caches.match('.'))||Response.error();}
    })());
    return;
  }
  /* Le cœur (CORE) : cache versionné d'abord, réseau en secours. ⚠️ Pré-cacher ne suffit pas,
     c'est cette branche qui SERT le cœur hors ligne. (journal : sw.js · pré-cacher ne servait à rien) */
  if(url.origin===self.location.origin&&COEUR.has(url.pathname)){
    e.respondWith((async()=>{
      const c=await caches.open(CACHE);
      const hit=await c.match(e.request,{ignoreSearch:true});
      if(hit)return hit;
      try{
        const r=await fetch(e.request);
        if(r&&r.ok)c.put(e.request,r.clone());
        return r;
      }catch(_){return (await caches.match(e.request,{ignoreSearch:true}))||Response.error();}
    })());
    return;
  }
  // audios, polices Google, récitation, icônes : cache d'abord
  const cacheFirst=url.pathname.indexOf('/audios-app-alaq/')>=0
    ||url.hostname==='fonts.googleapis.com'||url.hostname==='fonts.gstatic.com'||url.hostname==='cdn.jsdelivr.net'
    ||url.hostname==='cdn.islamic.network'  // la récitation streamée : mise en cache côté client, comme leurs conditions le demandent
    ||/\.(png|jpe?g|webp|mp3|mp4|woff2?)$/.test(url.pathname);
  if(cacheFirst){
    e.respondWith((async()=>{
      const hit=await caches.match(e.request);
      if(hit)return hit;
      try{
        const r=await fetch(e.request);
        // les IMAGES vont dans leur cache versionné ; sons, polices, récitation dans MEDIA
        if(r&&(r.ok||r.type==='opaque')){
          const img=/\.(png|jpe?g|webp|gif)$/.test(url.pathname);
          const c=await caches.open(img?IMGCACHE:MEDIA);c.put(e.request,r.clone());
        }
        return r;
      }catch(_){return Response.error();}
    })());
  }
});
