/* ALAQ service worker — hors ligne complet
   Stratégie :
   - index.html / navigation : réseau d'abord (toujours la dernière version en ligne),
     cache en secours (avion, mosquée sans réseau…)
   - audios, polices, icônes : cache d'abord (rapide), réseau en secours
   - les audios de la voix de Myriam sont pré-chargés à l'installation
   - la RÉCITATION n'est plus hébergée ici : elle est streamée depuis cdn.islamic.network
     et mise en cache au fil des versets écoutés (voir VOIX dans index.html) */
const CACHE='alaq-v185-2026-09-05';  // L'APP : versionné, purgé à chaque livraison
/* LES MÉDIAS : un cache À PART, JAMAIS purgé. Un mp3 ne change pas de contenu —
   ba-fatha-son-court.mp3 dira la même chose dans dix ans. Les ranger dans le cache
   versionné revenait à les jeter et à les racheter (8 Mo) à CHAQUE déploiement, sur
   chaque appareil. Ici ils se téléchargent une seule fois dans la vie de l'appareil. */
const MEDIA='alaq-medias';
/* LES IMAGES : un cache versionné À PART (10/08). Contrairement aux mp3, une icône
   RETOUCHÉE garde souvent son nom — dans MEDIA elle restait alors périmée à vie.
   Ici : une image change → IMGV s'incrémente → à l'activation l'ancien cache
   d'images est jeté entier et tout se retélécharge frais (quelques Mo d'icônes,
   rien à voir avec les 8 Mo d'audio qui ne bougent jamais). Plus de renommage
   obligatoire, plus de liste de purge à tenir pour les images. */
/* 🔴 RETOUCHÉES TROIS FOIS SOUS LE MÊME NOM (Myriam, 15/08 : « le test dans localhost
   me donne toujours les mêmes images »). Les 40 illustrations de l'unité 8 sont
   passées par trois régénérations — 8,1 Mo → 420 Ko, puis 384 px, puis sans tramage
   — toujours sous les noms qalam.png, himar.png… Chaque image est CACHE-D'ABORD
   (voir le fetch handler plus bas) : le navigateur a gardé la TOUTE PREMIÈRE version
   vue de chaque fichier, et rien sur le disque ne pouvait la déloger.
   Bumper IMGV renomme le cache (alaq-images-v1 → v2) : l'ancien ne correspond plus
   à rien, `activate` le jette, et chaque image repart chercher le réseau. C'est la
   règle que ce projet a déjà pour toute image retouchée sous le même nom — je l'ai
   moi-même oubliée trois fois de suite ici. */
const IMGV=17;
const IMGCACHE='alaq-images-v'+IMGV;
const CORE=['.','index.html','u8/u8.js','u8/u8.css','confidentialite.html','polices/polices.css','manifest.webmanifest','icon-192.png','icon-512.png','apple-touch-icon.png'];
const IMAGES=[ // icônes des disques de l'accueil — sans elles les disques sont vides
"images-app-alaq/icone-tb-lanterne-v1.png",
"images-app-alaq/icone-porte-v1.png",
"images-app-alaq/icone-main-glisse-v2.png",
"images-app-alaq/icone-ciel-dromadaire-v1.png",
"images-app-alaq/icone-tb-epi-v1.png",
"images-app-alaq/epi-pousse-anime-v1.webp",
"images-app-alaq/icone-tb-coeur-v1.png",
"images-app-alaq/icone-loupe-v1.png",
"images-app-alaq/icone-loupe-v1-clair.png",  // le jumeau du mode clair (02/09) : sans lui, la loupe est morte hors ligne sur le parchemin
"images-app-alaq/icone-tab-video.png",
"images-app-alaq/icone-tab-cartes.png",
"images-app-alaq/icone-tab-crayon.png",
"images-app-alaq/icone-tab-parchemin.png",
"images-app-alaq/icone-tab-puzzle.png",
"images-app-alaq/icone-tab-micro.png",
"images-app-alaq/icone-tab-etoiles.png",
"images-app-alaq/icone-tab2-lire.png",
"images-app-alaq/icone-tab2-qoran.png",
"images-app-alaq/icone-tab2-ecrire.png",
"badges/disque1.png",
"badges/unite1.png",
"badges/sourate1.png",
"badges/sansfaute.png",
"badges/unite-sansfaute.png",
"badges/ecusson-vierge.png",
"badges/lecons1.png",
"badges/lecons2.png",
"badges/lecons3.png",
"badges/lecons10.png",
"badges/lecons20.png",
"badges/lecons50.png",
"badges/lecons100.png",
"badges/lecons200.png",
"badges/lecons500.png",
"badges/lecons1000.png",
"badges/serie3.png",
"badges/serie7.png",
"badges/serie30.png",
"badges/serie120.png",
"badges/serie360.png",
"badges/revision.png",
"badges/revision3.png",
"badges/revision7.png",
"badges/revision30.png",
"badges/revision50.png",
"badges/revision120.png",
"badges/revision360.png",
"images-app-alaq/icone-prm-sons.png",
"images-app-alaq/icone-prm-objectif.png",
"images-app-alaq/icone-prm-apropos.png",
"images-app-alaq/icone-prm-voix.png",
"images-app-alaq/icone-ecran-corriger.png",
"images-app-alaq/icone-ecran-ghufran.png",
"images-app-alaq/icone-ecran-pousse.png",
"images-app-alaq/icone-ecran-compte.png",
"images-app-alaq/icone-menu-apprendre.png",
"images-app-alaq/icone-menu-cours.png",
"images-app-alaq/icone-menu-reviser.png",
"images-app-alaq/icone-menu-profil.png",
"images-app-alaq/icone-menu-parametres.png",
"images-app-alaq/icone-disq8-a-bilan.png",
"images-app-alaq/icone-disq7-c-bilan.png",
"images-app-alaq/icone-disq8-a-decouvrir.png",
"images-app-alaq/icone-disq7-c-decouvrir.png",
"images-app-alaq/icone-disq8-a-ecrire.png",
"images-app-alaq/icone-disq7-c-ecrire.png",
"images-app-alaq/icone-disq8-a-lire.png",
"images-app-alaq/icone-disq7-c-lire.png",
"images-app-alaq/icone-disq8-a-memoriser.png",
"images-app-alaq/icone-disq7-c-memoriser.png",
"images-app-alaq/icone-disq8-a-qoran.png",
"images-app-alaq/icone-disq7-c-qoran.png",
"images-app-alaq/icone-disq8-a-reviser.png",
"images-app-alaq/icone-disq7-c-reviser.png"
];
const AUDIOS=[
"audios-app-alaq/ain-alif-son-prolonge.mp3",
"audios-app-alaq/ain-damma-son-court.mp3",
"audios-app-alaq/ain-fatha-son-court.mp3",
"audios-app-alaq/ain-kasra-son-court.mp3",
"audios-app-alaq/ain-waw-son-prolonge.mp3",
"audios-app-alaq/ain-ya-son-prolonge.mp3",
"audios-app-alaq/alif-alif-son-prolonge.mp3",
"audios-app-alaq/alif-damma-son-court.mp3",
"audios-app-alaq/alif-fatha-son-court.mp3",
"audios-app-alaq/alif-kasra-son-court.mp3",
"audios-app-alaq/alif-waw-son-prolonge.mp3",
"audios-app-alaq/alif-ya-son-prolonge.mp3",
"audios-app-alaq/ba-alif-son-prolonge.mp3",
"audios-app-alaq/ba-damma-son-court.mp3",
"audios-app-alaq/ba-fatha-son-court.mp3",
"audios-app-alaq/ba-kasra-son-court.mp3",
"audios-app-alaq/ba-waw-son-prolonge.mp3",
"audios-app-alaq/ba-ya-son-prolonge.mp3",
"audios-app-alaq/dad-alif-son-prolonge.mp3",
"audios-app-alaq/dad-damma-son-court.mp3",
"audios-app-alaq/dad-fatha-son-court.mp3",
"audios-app-alaq/dad-kasra-son-court.mp3",
"audios-app-alaq/dad-waw-son-prolonge.mp3",
"audios-app-alaq/dad-ya-son-prolonge.mp3",
"audios-app-alaq/dal-alif-son-prolonge.mp3",
"audios-app-alaq/dal-damma-son-court.mp3",
"audios-app-alaq/dal-fatha-son-court.mp3",
"audios-app-alaq/dal-kasra-son-court.mp3",
"audios-app-alaq/dal-waw-son-prolonge.mp3",
"audios-app-alaq/dal-ya-son-prolonge.mp3",
"audios-app-alaq/dhal-alif-son-prolonge.mp3",
"audios-app-alaq/dhal-damma-son-court.mp3",
"audios-app-alaq/dhal-fatha-son-court.mp3",
"audios-app-alaq/dhal-kasra-son-court.mp3",
"audios-app-alaq/dhal-waw-son-prolonge.mp3",
"audios-app-alaq/dhal-ya-son-prolonge.mp3",
"audios-app-alaq/ghayn-alif-son-prolonge.mp3",
"audios-app-alaq/ghayn-damma-son-court.mp3",
"audios-app-alaq/ghayn-fatha-son-court.mp3",
"audios-app-alaq/ghayn-kasra-son-court.mp3",
"audios-app-alaq/ghayn-waw-son-prolonge.mp3",
"audios-app-alaq/ghayn-ya-son-prolonge.mp3",
"audios-app-alaq/ha-alif-son-prolonge.mp3",
"audios-app-alaq/ha-damma-son-court.mp3",
"audios-app-alaq/ha-fatha-son-court.mp3",
"audios-app-alaq/ha-kasra-son-court.mp3",
"audios-app-alaq/ha-waw-son-prolonge.mp3",
"audios-app-alaq/ha-ya-son-prolonge.mp3",
"audios-app-alaq/hha-alif-son-prolonge.mp3",
"audios-app-alaq/hha-damma-son-court.mp3",
"audios-app-alaq/hha-fatha-son-court.mp3",
"audios-app-alaq/hha-kasra-son-court.mp3",
"audios-app-alaq/hha-waw-son-prolonge.mp3",
"audios-app-alaq/hha-ya-son-prolonge.mp3",
// ===== lot « marque sonore » du 05/08/2026 : 19 consignes + 29 lettres × 2 voix,
// les 4 félicitations du combo × 2 voix, et le son de fin de leçon =====
// 17/08 — les 6 noms de lettres « -f » (voix IA) SORTENT du pré-cache et du dépôt :
// Myriam a enregistré les six, et l'app demande désormais le nom PLAT en premier.
// Leurs prises plates sont pré-cachées juste au-dessus, donc le hors ligne est intact.
"audios-app-alaq/felicit-moumtaz-f.mp3",
"audios-app-alaq/felicit-sahih-f.mp3",
"audios-app-alaq/felicit-rai-f.mp3",
"audios-app-alaq/felicit-allahumma-barik-f.mp3",
"audios-app-alaq/sfx-fin-lecon.mp3",
"audios-app-alaq/instr-assoc-haraka.mp3",
"audios-app-alaq/instr-associe.mp3",
"audios-app-alaq/instr-attache-6-dorees.mp3",
"audios-app-alaq/instr-attache-6.mp3",
"audios-app-alaq/instr-choisis.mp3",
"audios-app-alaq/instr-combine.mp3",
"audios-app-alaq/instr-costume-glisse.mp3",
"audios-app-alaq/instr-costumes.mp3",
"audios-app-alaq/instr-deux-fois-cartes.mp3",
"audios-app-alaq/instr-dragassoc.mp3",
"audios-app-alaq/instr-dragmad.mp3",
"audios-app-alaq/instr-ecoute-reponse.mp3",
"audios-app-alaq/instr-ecris-arabe.mp3",
"audios-app-alaq/instr-ecris-ecoute.mp3",
"audios-app-alaq/instr-explore-3.mp3",
"audios-app-alaq/instr-explore-cases.mp3",
"audios-app-alaq/instr-glisse-gd.mp3",
"audios-app-alaq/instr-haraka-intro.mp3",
"audios-app-alaq/instr-hp-choisis.mp3",
"audios-app-alaq/instr-info-chedda.mp3",
"audios-app-alaq/instr-info-lettres-empilees.mp3",
"audios-app-alaq/instr-info-soukoun.mp3",
"audios-app-alaq/instr-info-tanwin.mp3",
"audios-app-alaq/instr-intro-28-lettres.mp3",
"audios-app-alaq/instr-intro-bienvenue.mp3",
"audios-app-alaq/instr-intro-quiz.mp3",
"audios-app-alaq/instr-lettre-nom.mp3",
"audios-app-alaq/instr-madrasatoun.mp3",
"audios-app-alaq/instr-mot-ecoute.mp3",
"audios-app-alaq/instr-prolong-deux.mp3",
"audios-app-alaq/instr-prolong-dorees.mp3",
"audios-app-alaq/instr-prolong-intro.mp3",
"audios-app-alaq/instr-recite.mp3",
"audios-app-alaq/instr-son-long.mp3",
"audios-app-alaq/instr-spot-verset.mp3",
"audios-app-alaq/instr-stiles.mp3",
"audios-app-alaq/instr-touche-droite.mp3",
"audios-app-alaq/instr-trace.mp3",
"audios-app-alaq/instr-vtiles.mp3",
"audios-app-alaq/instr-vwrite.mp3",
"audios-app-alaq/kaf-alif-son-prolonge.mp3",
"audios-app-alaq/kaf-damma-son-court.mp3",
"audios-app-alaq/kaf-fatha-son-court.mp3",
"audios-app-alaq/kaf-kasra-son-court.mp3",
"audios-app-alaq/kaf-waw-son-prolonge.mp3",
"audios-app-alaq/kaf-ya-son-prolonge.mp3",
"audios-app-alaq/lam-alif-son-prolonge.mp3",
"audios-app-alaq/lam-damma-son-court.mp3",
"audios-app-alaq/lam-fatha-son-court.mp3",
"audios-app-alaq/lam-kasra-son-court.mp3",
"audios-app-alaq/lam-waw-son-prolonge.mp3",
"audios-app-alaq/lam-ya-son-prolonge.mp3",
"audios-app-alaq/lettre-alif-nom.mp3",
"audios-app-alaq/lettre-ayn-nom.mp3",
"audios-app-alaq/lettre-ba-nom.mp3",
"audios-app-alaq/lettre-dad-nom.mp3",
"audios-app-alaq/lettre-dal-nom.mp3",
"audios-app-alaq/lettre-dha-nom.mp3",
"audios-app-alaq/lettre-dhal-nom.mp3",
"audios-app-alaq/lettre-fa-nom.mp3",
"audios-app-alaq/lettre-ghayn-nom.mp3",
"audios-app-alaq/lettre-ha-nom.mp3",
"audios-app-alaq/lettre-hamza-nom.mp3",
"audios-app-alaq/lettre-hha-nom.mp3",
"audios-app-alaq/lettre-jim-nom.mp3",
"audios-app-alaq/lettre-kaf-nom.mp3",
"audios-app-alaq/lettre-kha-nom.mp3",
"audios-app-alaq/lettre-lam-nom.mp3",
"audios-app-alaq/lettre-mim-nom.mp3",
"audios-app-alaq/lettre-nun-nom.mp3",
"audios-app-alaq/lettre-qaf-nom.mp3",
"audios-app-alaq/lettre-ra-nom.mp3",
"audios-app-alaq/lettre-sad-nom.mp3",
"audios-app-alaq/lettre-shin-nom.mp3",
"audios-app-alaq/lettre-sin-nom.mp3",
"audios-app-alaq/lettre-ta-nom.mp3",
"audios-app-alaq/lettre-tha-nom.mp3",
"audios-app-alaq/lettre-tta-nom.mp3",
"audios-app-alaq/lettre-waw-nom.mp3",
"audios-app-alaq/lettre-ya-nom.mp3",
"audios-app-alaq/lettre-zay-nom.mp3",
"audios-app-alaq/mim-alif-son-prolonge.mp3",
"audios-app-alaq/mim-damma-son-court.mp3",
"audios-app-alaq/mim-fatha-son-court.mp3",
"audios-app-alaq/mim-kasra-son-court.mp3",
"audios-app-alaq/mim-waw-son-prolonge.mp3",
"audios-app-alaq/mim-ya-son-prolonge.mp3",
"audios-app-alaq/mot-aalim.mp3",
"audios-app-alaq/mot-addallin.mp3",
"audios-app-alaq/mot-ahad.mp3",
"audios-app-alaq/mot-alam.mp3",
"audios-app-alaq/mot-alamoun.mp3",
"audios-app-alaq/mot-alayhim.mp3",
"audios-app-alaq/mot-alhamdu.mp3",
"audios-app-alaq/mot-alim.mp3",
/* les deux mots du jeu de tri de la leçon 3 (14/08) — la leçon doit tourner hors ligne */
"audios-app-alaq/mot-alladhina.mp3",
"audios-app-alaq/mot-allah.mp3",
"audios-app-alaq/mot-almaghdub.mp3",
"audios-app-alaq/mot-amal.mp3",
"audios-app-alaq/mot-aman.mp3",
"audios-app-alaq/mot-amin.mp3",
"audios-app-alaq/mot-amr.mp3",
"audios-app-alaq/mot-anamta.mp3",
"audios-app-alaq/mot-annas.mp3",
"audios-app-alaq/mot-arabi.mp3",
"audios-app-alaq/mot-arrahim.mp3",
"audios-app-alaq/mot-arrahman.mp3",
"audios-app-alaq/mot-assamad.mp3",
"audios-app-alaq/mot-audhu.mp3",
"audios-app-alaq/mot-ayn.mp3",
"audios-app-alaq/mot-bab.mp3",
"audios-app-alaq/mot-qalamul-bint.mp3",
"audios-app-alaq/mot-qalamul-walad.mp3",
"audios-app-alaq/mot-tayrul-walad.mp3",
"audios-app-alaq/mot-tayrul-bint.mp3",
"audios-app-alaq/mot-hablul-himar.mp3",
"audios-app-alaq/mot-hablul-bint.mp3",
"audios-app-alaq/mot-bismillah.mp3",
"audios-app-alaq/mot-alhamdulillah.mp3",
"audios-app-alaq/mot-bi.mp3",
"audios-app-alaq/mot-li.mp3",
"audios-app-alaq/mot-ala.mp3",
"audios-app-alaq/mot-ismoun.mp3",
"audios-app-alaq/mot-bi-ismin.mp3",
"audios-app-alaq/mot-lillah.mp3",
"audios-app-alaq/mot-hum.mp3",
"audios-app-alaq/mot-lilbint.mp3",
"audios-app-alaq/mot-lilwalad.mp3",
"audios-app-alaq/mot-lilhimar.mp3",
"audios-app-alaq/mot-lilumm.mp3",
"audios-app-alaq/mot-albint.mp3",
"audios-app-alaq/mot-alwalad.mp3",
"audios-app-alaq/mot-alumm.mp3",
"audios-app-alaq/mot-alalbayt.mp3",
"audios-app-alaq/mot-alalmaktab.mp3",
"audios-app-alaq/mot-alannabat.mp3",
"audios-app-alaq/mot-alalhimar.mp3",
"audios-app-alaq/mot-alalbab.mp3",
"audios-app-alaq/mot-maktab.mp3",
"audios-app-alaq/mot-waladyaktubbilqalam.mp3",
"audios-app-alaq/mot-almaa.mp3",
"audios-app-alaq/mot-waladyatawaddabilmaa.mp3",
"audios-app-alaq/mot-atturab.mp3",
"audios-app-alaq/mot-waladyatayammambitturab.mp3",
"audios-app-alaq/mot-binttatasallaqbilhabl.mp3",
"audios-app-alaq/mot-waladyaktub.mp3",
"audios-app-alaq/mot-waladyatawadda.mp3",
"audios-app-alaq/mot-waladyatayammam.mp3",
"audios-app-alaq/mot-nabat.mp3",
"audios-app-alaq/mot-attayralalbayt.mp3",
"audios-app-alaq/mot-rummanlilbint.mp3",
"audios-app-alaq/mot-rummanlilwalad.mp3",
"audios-app-alaq/mot-qalamlilwalad.mp3",
"audios-app-alaq/mot-tinlilhimar.mp3",
"audios-app-alaq/mot-rummanlilumm.mp3",
"audios-app-alaq/mot-qalamlilumm.mp3",
"audios-app-alaq/mot-tinlilumm.mp3",
"audios-app-alaq/mot-bilqalam.mp3",
"audios-app-alaq/mot-bilmaa.mp3",
"audios-app-alaq/mot-bitturab.mp3",
"audios-app-alaq/mot-bilhabl.mp3",
"audios-app-alaq/mot-bilyad.mp3",
"audios-app-alaq/mot-tayralalbayt.mp3",
"audios-app-alaq/mot-almaktab.mp3",
"audios-app-alaq/mot-qalamalalmaktab.mp3",
"audios-app-alaq/mot-hablilhimar.mp3",
"audios-app-alaq/mot-aktub.mp3",
"audios-app-alaq/mot-annabat.mp3",
"audios-app-alaq/mot-nahlaalanabat.mp3",
"audios-app-alaq/mot-bint.mp3",
"audios-app-alaq/mot-qalamlilbint.mp3",
"audios-app-alaq/mot-walad.mp3",
"audios-app-alaq/mot-tinlilwalad.mp3",
"audios-app-alaq/mot-hablalalmaktab.mp3",
"audios-app-alaq/mot-arrahmani.mp3",
"audios-app-alaq/mot-arrahimi.mp3",
"audios-app-alaq/mot-addini.mp3",
"audios-app-alaq/mot-assirata.mp3",
"audios-app-alaq/mot-almustaqima.mp3",
"audios-app-alaq/mot-alamin.mp3",
"audios-app-alaq/mot-qalam.mp3",
"audios-app-alaq/mot-alqalam.mp3",
"audios-app-alaq/mot-qamar.mp3",
"audios-app-alaq/mot-alqamar.mp3",
"audios-app-alaq/faux-alqamar.mp3",
"audios-app-alaq/mot-albab.mp3",
"audios-app-alaq/mot-yad.mp3",
"audios-app-alaq/mot-alyad.mp3",
"audios-app-alaq/faux-alyad.mp3",
"audios-app-alaq/mot-bayt.mp3",
"audios-app-alaq/mot-albayt.mp3",
"audios-app-alaq/faux-albayt.mp3",
"audios-app-alaq/mot-habl.mp3",
"audios-app-alaq/mot-alhabl.mp3",
"audios-app-alaq/mot-himar.mp3",
"audios-app-alaq/mot-alhimar.mp3",
"audios-app-alaq/faux-alhimar.mp3",
"audios-app-alaq/mot-dalw.mp3",
"audios-app-alaq/mot-aldalw.mp3",
"audios-app-alaq/faux-aldalw.mp3",
"audios-app-alaq/mot-dar.mp3",
"audios-app-alaq/mot-aldar.mp3",
"audios-app-alaq/mot-tayr.mp3",
"audios-app-alaq/mot-altayr.mp3",
"audios-app-alaq/mot-rumman.mp3",
"audios-app-alaq/mot-alrumman.mp3",
"audios-app-alaq/faux-alrumman.mp3",
"audios-app-alaq/mot-nahl.mp3",
"audios-app-alaq/mot-alnahl.mp3",
"audios-app-alaq/mot-dhahab.mp3",
"audios-app-alaq/mot-aldhahab.mp3",
"audios-app-alaq/faux-aldhahab.mp3",
"audios-app-alaq/mot-tin.mp3",
"audios-app-alaq/mot-altin.mp3",
"audios-app-alaq/mot-bismi.mp3",
"audios-app-alaq/mot-dars.mp3",
"audios-app-alaq/mot-dhahaba.mp3",
"audios-app-alaq/mot-din.mp3",
"audios-app-alaq/mot-ghasiq.mp3",
"audios-app-alaq/mot-ghayb.mp3",
"audios-app-alaq/mot-ghayr.mp3",
"audios-app-alaq/mot-hasid.mp3",
"audios-app-alaq/mot-hatab.mp3",
"audios-app-alaq/mot-huwa.mp3",
"audios-app-alaq/mot-idha.mp3",
"audios-app-alaq/mot-ihdina.mp3",
"audios-app-alaq/mot-ilah.mp3",
"audios-app-alaq/mot-iman.mp3",
"audios-app-alaq/mot-iyyaka.mp3",
"audios-app-alaq/mot-karim.mp3",
"audios-app-alaq/mot-kasaba.mp3",
"audios-app-alaq/mot-laban.mp3",
"audios-app-alaq/mot-lamma.mp3",
"audios-app-alaq/mot-lawm.mp3",
"audios-app-alaq/mot-lawn.mp3",
"audios-app-alaq/mot-layl.mp3",
"audios-app-alaq/mot-lin.mp3",
"audios-app-alaq/mot-maalik.mp3",
"audios-app-alaq/mot-madrasatoun.mp3",
"audios-app-alaq/mot-mal.mp3",
"audios-app-alaq/mot-malik.mp3",
"audios-app-alaq/mot-mamnoun.mp3",
"audios-app-alaq/mot-manal.mp3",
"audios-app-alaq/mot-manam.mp3",
"audios-app-alaq/mot-mann.mp3",
"audios-app-alaq/mot-mustaqim.mp3",
"audios-app-alaq/mot-naabudu.mp3",
"audios-app-alaq/mot-nabi.mp3",
"audios-app-alaq/mot-naml.mp3",
"audios-app-alaq/mot-nastain.mp3",
"audios-app-alaq/mot-nil.mp3",
"audios-app-alaq/mot-noun.mp3",
"audios-app-alaq/mot-oulama.mp3",
"audios-app-alaq/mot-qul.mp3",
"audios-app-alaq/mot-rabb.mp3",
"audios-app-alaq/mot-rabi.mp3",
"audios-app-alaq/mot-sabr.mp3",
"audios-app-alaq/mot-sirat.mp3",
"audios-app-alaq/mot-sudur.mp3",
"audios-app-alaq/mot-tabba.mp3",
"audios-app-alaq/mot-tariq.mp3",
"audios-app-alaq/mot-umm.mp3",
"audios-app-alaq/mot-umr.mp3",
"audios-app-alaq/mot-uqad.mp3",
"audios-app-alaq/mot-waqaba.mp3",
"audios-app-alaq/mot-yamin.mp3",
"audios-app-alaq/mot-yawm.mp3",
"audios-app-alaq/nom-alalim.mp3",
"audios-app-alaq/nom-almalik.mp3",
"audios-app-alaq/nom-almumin.mp3",
"audios-app-alaq/nom-arrahim.mp3",
"audios-app-alaq/nom-arrahman.mp3",
"audios-app-alaq/nom-assalam.mp3",
"audios-app-alaq/nom-addarr.mp3",
"audios-app-alaq/nom-aladl.mp3",
"audios-app-alaq/nom-alaliyy.mp3",
"audios-app-alaq/nom-alawwal.mp3",
"audios-app-alaq/nom-albadi.mp3",
"audios-app-alaq/nom-albaqi.mp3",
"audios-app-alaq/nom-albari.mp3",
"audios-app-alaq/nom-albarr.mp3",
"audios-app-alaq/nom-albasir.mp3",
"audios-app-alaq/nom-albasit.mp3",
"audios-app-alaq/nom-albatin.mp3",
"audios-app-alaq/nom-alghaniyy.mp3",
"audios-app-alaq/nom-alhadi.mp3",
"audios-app-alaq/nom-alhakam.mp3",
"audios-app-alaq/nom-alhakim.mp3",
"audios-app-alaq/nom-alhalim.mp3",
"audios-app-alaq/nom-alhamid.mp3",
"audios-app-alaq/nom-alhaqq.mp3",
"audios-app-alaq/nom-alhasib.mp3",
"audios-app-alaq/nom-alhayy.mp3",
"audios-app-alaq/nom-alkabir.mp3",
"audios-app-alaq/nom-alkarim.mp3",
"audios-app-alaq/nom-allah.mp3",
"audios-app-alaq/nom-almani.mp3",
"audios-app-alaq/nom-almatin.mp3",
"audios-app-alaq/nom-almubdi.mp3",
"audios-app-alaq/nom-almudhill.mp3",
"audios-app-alaq/nom-almughni.mp3",
"audios-app-alaq/nom-almuhaymin.mp3",
"audios-app-alaq/nom-almuhsi.mp3",
"audios-app-alaq/nom-almuhyi.mp3",
"audios-app-alaq/nom-almuid.mp3",
"audios-app-alaq/nom-almumit.mp3",
"audios-app-alaq/nom-almuntaqim.mp3",
"audios-app-alaq/nom-almuqaddim.mp3",
"audios-app-alaq/nom-almuqit.mp3",
"audios-app-alaq/nom-almuqsit.mp3",
"audios-app-alaq/nom-almuqtadir.mp3",
"audios-app-alaq/nom-almusawwir.mp3",
"audios-app-alaq/nom-almutaali.mp3",
"audios-app-alaq/nom-almutakabbir.mp3",
"audios-app-alaq/nom-alqabid.mp3",
"audios-app-alaq/nom-alqadir.mp3",
"audios-app-alaq/nom-alqahhar.mp3",
"audios-app-alaq/nom-alqawiyy.mp3",
"audios-app-alaq/nom-alqayyum.mp3",
"audios-app-alaq/nom-alquddus.mp3",
"audios-app-alaq/nom-alwadud.mp3",
"audios-app-alaq/nom-alwahhab.mp3",
"audios-app-alaq/nom-alwahid.mp3",
"audios-app-alaq/nom-alwakil.mp3",
"audios-app-alaq/nom-alwali.mp3",
"audios-app-alaq/nom-alwaliyy.mp3",
"audios-app-alaq/nom-alwasi.mp3",
"audios-app-alaq/nom-annur.mp3",
"audios-app-alaq/nom-arraqib.mp3",
"audios-app-alaq/nom-assabur.mp3",
"audios-app-alaq/nom-assamad.mp3",
"audios-app-alaq/nom-assami.mp3",
"audios-app-alaq/nom-attawwab.mp3",
"audios-app-alaq/nom-malikalmulk.mp3",
"audios-app-alaq/noun-alif-son-prolonge.mp3",
"audios-app-alaq/noun-damma-son-court.mp3",
"audios-app-alaq/noun-fatha-son-court.mp3",
"audios-app-alaq/noun-kasra-son-court.mp3",
"audios-app-alaq/noun-waw-son-prolonge.mp3",
"audios-app-alaq/noun-ya-son-prolonge.mp3",
"audios-app-alaq/qaf-alif-son-prolonge.mp3",
"audios-app-alaq/qaf-damma-son-court.mp3",
"audios-app-alaq/qaf-fatha-son-court.mp3",
"audios-app-alaq/qaf-kasra-son-court.mp3",
"audios-app-alaq/qaf-waw-son-prolonge.mp3",
"audios-app-alaq/qaf-ya-son-prolonge.mp3",
"audios-app-alaq/ra-alif-son-prolonge.mp3",
"audios-app-alaq/ra-damma-son-court.mp3",
"audios-app-alaq/ra-fatha-son-court.mp3",
"audios-app-alaq/ra-kasra-son-court.mp3",
"audios-app-alaq/ra-waw-son-prolonge.mp3",
"audios-app-alaq/ra-ya-son-prolonge.mp3",
"audios-app-alaq/sad-alif-son-prolonge.mp3",
"audios-app-alaq/sad-damma-son-court.mp3",
"audios-app-alaq/sad-fatha-son-court.mp3",
"audios-app-alaq/sad-kasra-son-court.mp3",
"audios-app-alaq/sad-waw-son-prolonge.mp3",
"audios-app-alaq/sad-ya-son-prolonge.mp3",
"audios-app-alaq/sfx-bonne-reponse.mp3",
"audios-app-alaq/sfx-erreur.mp3",
"audios-app-alaq/mim-fatha-son-court-f.mp3",
"audios-app-alaq/mim-kasra-son-court-f.mp3",
"audios-app-alaq/mim-damma-son-court-f.mp3",
"audios-app-alaq/mim-alif-son-prolonge-f.mp3",
"audios-app-alaq/mim-ya-son-prolonge-f.mp3",
"audios-app-alaq/mim-waw-son-prolonge-f.mp3",
"audios-app-alaq/mot-madrasatoun.mp3",
"audios-app-alaq/sin-alif-son-prolonge.mp3",
"audios-app-alaq/sin-damma-son-court.mp3",
"audios-app-alaq/sin-fatha-son-court.mp3",
"audios-app-alaq/sin-kasra-son-court.mp3",
"audios-app-alaq/sin-waw-son-prolonge.mp3",
"audios-app-alaq/sin-ya-son-prolonge.mp3",
"audios-app-alaq/ta-alif-son-prolonge.mp3",
"audios-app-alaq/ta-damma-son-court.mp3",
"audios-app-alaq/ta-fatha-son-court.mp3",
"audios-app-alaq/ta-kasra-son-court.mp3",
"audios-app-alaq/ta-waw-son-prolonge.mp3",
"audios-app-alaq/ta-ya-son-prolonge.mp3",
"audios-app-alaq/tta-alif-son-prolonge.mp3",
"audios-app-alaq/tta-damma-son-court.mp3",
"audios-app-alaq/tta-fatha-son-court.mp3",
"audios-app-alaq/tta-kasra-son-court.mp3",
"audios-app-alaq/tta-waw-son-prolonge.mp3",
"audios-app-alaq/tta-ya-son-prolonge.mp3",
"audios-app-alaq/voyelle-a.mp3",
"audios-app-alaq/voyelle-i.mp3",
"audios-app-alaq/voyelle-ou.mp3",
"audios-app-alaq/waw-alif-son-prolonge.mp3",
"audios-app-alaq/waw-damma-son-court.mp3",
"audios-app-alaq/waw-fatha-son-court.mp3",
"audios-app-alaq/waw-kasra-son-court.mp3",
"audios-app-alaq/waw-waw-son-prolonge.mp3",
"audios-app-alaq/waw-ya-son-prolonge.mp3",
"audios-app-alaq/ya-alif-son-prolonge.mp3",
"audios-app-alaq/ya-damma-son-court.mp3",
"audios-app-alaq/ya-fatha-son-court.mp3",
"audios-app-alaq/ya-kasra-son-court.mp3",
"audios-app-alaq/ya-waw-son-prolonge.mp3",
"audios-app-alaq/ya-ya-son-prolonge.mp3"
];

self.addEventListener('install',e=>{
  e.waitUntil((async()=>{
    const c=await caches.open(CACHE);
    await c.addAll(CORE);   // le cœur SEULEMENT : l'installation doit être rapide
    self.skipWaiting();
  })());
});
/* Les 301 audios + les icônes sont pré-chargés APRÈS le premier rendu : la page envoie
   « precache » quand elle est affichée. Avant, ils saturaient le réseau pendant le chargement
   (écran blanc à chaque déploiement). */
let _preFait=false;
/* Six téléchargements à la fois, pas 360. Lancer toute la liste d'un coup ne la rendait
   pas plus rapide — le navigateur la met de toute façon en file — mais cette file entrait
   en concurrence avec ce dont l'app a besoin au même instant : Supabase, les polices, et
   désormais la récitation streamée. Et l'on SAUTE ce qui est déjà là : au deuxième
   passage, c'est 360 lectures de cache, zéro requête réseau. */
async function enFile(liste,c,n){
  let i=0;
  const ouvrier=async()=>{
    while(i<liste.length){
      const u=liste[i++];
      try{ if(await c.match(u))continue; await c.add(u); }catch(_){ } // un 404 ne doit rien casser
    }
  };
  await Promise.all(Array.from({length:n},ouvrier));
}
async function precacheLourd(){
  if(_preFait)return; _preFait=true;
  await enFile(IMAGES,await caches.open(IMGCACHE),6); // les images dans LEUR cache versionné
  await enFile(AUDIOS,await caches.open(MEDIA),6);
}
self.addEventListener('message',e=>{ if(e.data==='precache')e.waitUntil(precacheLourd()); });
self.addEventListener('activate',e=>{
  e.waitUntil((async()=>{
    const keys=await caches.keys();
    // MEDIA survit aux livraisons ; IMGCACHE survit tant qu'IMGV ne bouge pas
    await Promise.all(keys.filter(k=>k!==CACHE&&k!==MEDIA&&k!==IMGCACHE).map(k=>caches.delete(k)));
    // ménage UNE fois : les images historiquement rangées dans MEDIA (jamais purgé)
    // sont celles qui restaient périmées à vie sur les appareils — on les en sort,
    // elles vivent désormais dans IMGCACHE.
    try{
      const md=await caches.open(MEDIA);
      const ks=await md.keys();
      await Promise.all(ks.filter(rq=>/\.(png|jpe?g|webp|gif)$/.test(new URL(rq.url).pathname))
        .map(rq=>md.delete(rq)));
    }catch(_){ }
    // ⚠️ MEDIA n'est jamais purgé — donc un fichier REMPLACÉ sous le même nom y reste
    // périmé pour toujours. Purge CIBLÉE de TOUS les remplacés (liste vérifiée au blob git
    // le 08/08 : 7 fichiers). Les deux sfx du 05/08 manquaient — c'est pour ça que
    // l'iPhone de Myriam jouait encore l'أَحْسَنْتِ (voix homme) du 13/07 à chaque bonne
    // réponse, quel que soit le contenu poussé depuis. Un fichier re-déposé sous le
    // même nom DOIT rejoindre cette liste (ou changer de nom).
    const m=await caches.open(MEDIA);
    await Promise.all(['lettre-alif-nom-f.mp3','lettre-alif-nom-h.mp3',
      'lettre-fa-nom-f.mp3','lettre-fa-nom-h.mp3','mot-madrasatoun.mp3',
      'sfx-bonne-reponse.mp3','sfx-fin-lecon.mp3',
      /* 17/08 — les 5 autres noms de lettres en voix IA, RETIRÉS du dépôt le même jour.
         `sayLetterName` demande le nom PLAT d'abord, mais retombe sur le « -f » si la
         prise plate échoue (hors ligne, cache incomplet) : sans cette purge, un appareil
         qui a entendu l'IA la garderait en secours à vie. */
      'lettre-ayn-nom-f.mp3','lettre-hamza-nom-f.mp3','lettre-lam-nom-f.mp3',
      'lettre-mim-nom-f.mp3','lettre-waw-nom-f.mp3',
      /* 10/08 tard — les syllabes IA RETIRÉES (« c'est la cata », Myriam) + 4 mots à
         revoir : servis quelques heures, ils doivent sortir du cache des appareils
         qui les ont entendus, sinon ils y restent à vie (cache MEDIA). */
      'lam-fatha-son-court-f.mp3',
      'lam-kasra-son-court-f.mp3',
      'lam-damma-son-court-f.mp3',
      'lam-alif-son-prolonge-f.mp3',
      'lam-ya-son-prolonge-f.mp3',
      'lam-waw-son-prolonge-f.mp3',
      'noun-fatha-son-court-f.mp3',
      'noun-kasra-son-court-f.mp3',
      'noun-damma-son-court-f.mp3',
      'noun-alif-son-prolonge-f.mp3',
      'noun-ya-son-prolonge-f.mp3',
      'noun-waw-son-prolonge-f.mp3',
      'ya-fatha-son-court-f.mp3',
      'ya-kasra-son-court-f.mp3',
      'ya-damma-son-court-f.mp3',
      'ya-alif-son-prolonge-f.mp3',
      'ya-ya-son-prolonge-f.mp3',
      'ya-waw-son-prolonge-f.mp3',
      'waw-fatha-son-court-f.mp3',
      'waw-kasra-son-court-f.mp3',
      'waw-damma-son-court-f.mp3',
      'waw-alif-son-prolonge-f.mp3',
      'waw-ya-son-prolonge-f.mp3',
      'waw-waw-son-prolonge-f.mp3',
      'ba-fatha-son-court-f.mp3',
      'ba-kasra-son-court-f.mp3',
      'ba-damma-son-court-f.mp3',
      'ba-alif-son-prolonge-f.mp3',
      'ba-ya-son-prolonge-f.mp3',
      'ba-waw-son-prolonge-f.mp3',
      'ra-fatha-son-court-f.mp3',
      'ra-kasra-son-court-f.mp3',
      'ra-damma-son-court-f.mp3',
      'ra-alif-son-prolonge-f.mp3',
      'ra-ya-son-prolonge-f.mp3',
      'ra-waw-son-prolonge-f.mp3',
      'ain-fatha-son-court-f.mp3',
      'ain-kasra-son-court-f.mp3',
      'ain-damma-son-court-f.mp3',
      'ain-alif-son-prolonge-f.mp3',
      'ain-ya-son-prolonge-f.mp3',
      'ain-waw-son-prolonge-f.mp3',
      'sin-fatha-son-court-f.mp3',
      'sin-kasra-son-court-f.mp3',
      'sin-damma-son-court-f.mp3',
      'sin-alif-son-prolonge-f.mp3',
      'sin-ya-son-prolonge-f.mp3',
      'sin-waw-son-prolonge-f.mp3',
      'dal-fatha-son-court-f.mp3',
      'dal-kasra-son-court-f.mp3',
      'dal-damma-son-court-f.mp3',
      'dal-alif-son-prolonge-f.mp3',
      'dal-ya-son-prolonge-f.mp3',
      'dal-waw-son-prolonge-f.mp3',
      'kaf-fatha-son-court-f.mp3',
      'kaf-kasra-son-court-f.mp3',
      'kaf-damma-son-court-f.mp3',
      'kaf-alif-son-prolonge-f.mp3',
      'kaf-ya-son-prolonge-f.mp3',
      'kaf-waw-son-prolonge-f.mp3',
      'hha-fatha-son-court-f.mp3',
      'hha-kasra-son-court-f.mp3',
      'hha-damma-son-court-f.mp3',
      'hha-alif-son-prolonge-f.mp3',
      'hha-ya-son-prolonge-f.mp3',
      'hha-waw-son-prolonge-f.mp3',
      'tta-fatha-son-court-f.mp3',
      'tta-kasra-son-court-f.mp3',
      'tta-damma-son-court-f.mp3',
      'tta-alif-son-prolonge-f.mp3',
      'tta-ya-son-prolonge-f.mp3',
      'tta-waw-son-prolonge-f.mp3',
      'qaf-fatha-son-court-f.mp3',
      'qaf-kasra-son-court-f.mp3',
      'qaf-damma-son-court-f.mp3',
      'qaf-alif-son-prolonge-f.mp3',
      'qaf-ya-son-prolonge-f.mp3',
      'qaf-waw-son-prolonge-f.mp3',
      'ta-fatha-son-court-f.mp3',
      'ta-kasra-son-court-f.mp3',
      'ta-damma-son-court-f.mp3',
      'ta-alif-son-prolonge-f.mp3',
      'ta-ya-son-prolonge-f.mp3',
      'ta-waw-son-prolonge-f.mp3',
      'sad-fatha-son-court-f.mp3',
      'sad-kasra-son-court-f.mp3',
      'sad-damma-son-court-f.mp3',
      'sad-alif-son-prolonge-f.mp3',
      'sad-ya-son-prolonge-f.mp3',
      'sad-waw-son-prolonge-f.mp3',
      'ghayn-fatha-son-court-f.mp3',
      'ghayn-kasra-son-court-f.mp3',
      'ghayn-damma-son-court-f.mp3',
      'ghayn-alif-son-prolonge-f.mp3',
      'ghayn-ya-son-prolonge-f.mp3',
      'ghayn-waw-son-prolonge-f.mp3',
      'ha-fatha-son-court-f.mp3',
      'ha-kasra-son-court-f.mp3',
      'ha-damma-son-court-f.mp3',
      'ha-alif-son-prolonge-f.mp3',
      'ha-ya-son-prolonge-f.mp3',
      'ha-waw-son-prolonge-f.mp3',
      'dhal-fatha-son-court-f.mp3',
      'dhal-kasra-son-court-f.mp3',
      'dhal-damma-son-court-f.mp3',
      'dhal-alif-son-prolonge-f.mp3',
      'dhal-ya-son-prolonge-f.mp3',
      'dhal-waw-son-prolonge-f.mp3',
      'dad-fatha-son-court-f.mp3',
      'dad-kasra-son-court-f.mp3',
      'dad-damma-son-court-f.mp3',
      'dad-alif-son-prolonge-f.mp3',
      'dad-ya-son-prolonge-f.mp3',
      'dad-waw-son-prolonge-f.mp3',
      'mot-kasaba-f.mp3',
      'mot-allah-f.mp3',
      'mot-alladhina-f.mp3',
      'mot-addallin-f.mp3',
      /* 15/08 — les prises de Myriam remplacent des
         fichiers déjà servis : sans cette liste, les appareils qui les ont entendus
         garderaient l'ancienne voix à vie (cache MEDIA, jamais purgé). */
      'dad-alif-son-prolonge.mp3',
      'dad-damma-son-court.mp3',
      'dad-fatha-son-court.mp3',
      'dad-kasra-son-court.mp3',
      'dad-waw-son-prolonge.mp3',
      'dad-ya-son-prolonge.mp3',
      'dhal-alif-son-prolonge.mp3',
      'dhal-damma-son-court.mp3',
      'dhal-fatha-son-court.mp3',
      'dhal-kasra-son-court.mp3',
      'dhal-waw-son-prolonge.mp3',
      'dhal-ya-son-prolonge.mp3',
      'ghayn-alif-son-prolonge.mp3',
      'ghayn-damma-son-court.mp3',
      'ghayn-fatha-son-court.mp3',
      'ghayn-kasra-son-court.mp3',
      'ghayn-waw-son-prolonge.mp3',
      'ghayn-ya-son-prolonge.mp3',
      'ha-alif-son-prolonge.mp3',
      'ha-damma-son-court.mp3',
      'ha-fatha-son-court.mp3',
      'ha-kasra-son-court.mp3',
      'ha-waw-son-prolonge.mp3',
      'ha-ya-son-prolonge.mp3',
      'hha-alif-son-prolonge.mp3',
      'hha-damma-son-court.mp3',
      'hha-fatha-son-court.mp3',
      'hha-kasra-son-court.mp3',
      'hha-waw-son-prolonge.mp3',
      'hha-ya-son-prolonge.mp3',
      'kaf-ya-son-prolonge.mp3',
      'lettre-dad-nom.mp3',
      'lettre-dad-nom-f.mp3',
      'lettre-dhal-nom.mp3',
      'lettre-dhal-nom-f.mp3',
      'lettre-ghayn-nom.mp3',
      'lettre-ghayn-nom-f.mp3',
      'lettre-ha-nom.mp3',
      'lettre-ha-nom-f.mp3',
      'lettre-hha-nom.mp3',
      'lettre-hha-nom-f.mp3',
      'lettre-qaf-nom.mp3',
      'lettre-qaf-nom-f.mp3',
      'lettre-sad-nom.mp3',
      'lettre-sad-nom-f.mp3',
      'lettre-ta-nom.mp3',
      'lettre-ta-nom-f.mp3',
      'lettre-tta-nom.mp3',
      'lettre-tta-nom-f.mp3',
      'mot-ahad.mp3',
      'mot-ahad-f.mp3',
      'mot-alayhim.mp3',
      'mot-alayhim-f.mp3',
      'mot-alhamdu.mp3',
      'mot-alhamdu-f.mp3',
      'mot-alladhina.mp3',
      'mot-allah.mp3',
      'mot-anamta.mp3',
      'mot-anamta-f.mp3',
      'mot-arrahim.mp3',
      'mot-arrahim-f.mp3',
      'mot-arrahman.mp3',
      'mot-arrahman-f.mp3',
      'mot-assamad.mp3',
      'mot-assamad-f.mp3',
      'mot-audhu.mp3',
      'mot-audhu-f.mp3',
      'mot-dhahaba.mp3',
      'mot-dhahaba-f.mp3',
      'mot-ghasiq.mp3',
      'mot-ghasiq-f.mp3',
      'mot-ghayb.mp3',
      'mot-ghayb-f.mp3',
      'mot-ghayr.mp3',
      'mot-ghayr-f.mp3',
      'mot-hasid.mp3',
      'mot-hasid-f.mp3',
      'mot-hatab.mp3',
      'mot-hatab-f.mp3',
      'mot-huwa.mp3',
      'mot-huwa-f.mp3',
      'mot-idha.mp3',
      'mot-idha-f.mp3',
      'mot-ihdina.mp3',
      'mot-ihdina-f.mp3',
      'mot-ilah.mp3',
      'mot-ilah-f.mp3',
      'mot-ilayna-f.mp3',
      'mot-imam-f.mp3',
      'mot-mustaqim.mp3',
      'mot-mustaqim-f.mp3',
      'mot-nastain.mp3',
      'mot-nastain-f.mp3',
      'mot-qul.mp3',
      'mot-qul-f.mp3',
      'mot-sabr.mp3',
      'mot-sabr-f.mp3',
      'mot-sirat.mp3',
      'mot-sirat-f.mp3',
      'mot-sudur.mp3',
      'mot-sudur-f.mp3',
      'mot-tabba.mp3',
      'mot-tabba-f.mp3',
      'mot-tariq.mp3',
      'mot-tariq-f.mp3',
      'mot-uqad.mp3',
      'mot-uqad-f.mp3',
      'mot-waqaba.mp3',
      'mot-waqaba-f.mp3',
      'nom-addarr.mp3',
      'nom-aladl.mp3',
      'nom-alalim.mp3',
      'nom-alaliyy.mp3',
      'nom-alawwal.mp3',
      'nom-albadi.mp3',
      'nom-albaqi.mp3',
      'nom-albari.mp3',
      'nom-albarr.mp3',
      'nom-albasir.mp3',
      'nom-albasit.mp3',
      'nom-albatin.mp3',
      'nom-alghaniyy.mp3',
      'nom-alhadi.mp3',
      'nom-alhakam.mp3',
      'nom-alhakim.mp3',
      'nom-alhalim.mp3',
      'nom-alhamid.mp3',
      'nom-alhaqq.mp3',
      'nom-alhasib.mp3',
      'nom-alhayy.mp3',
      'nom-alkabir.mp3',
      'nom-alkarim.mp3',
      'nom-allah.mp3',
      'nom-almalik.mp3',
      'nom-almani.mp3',
      'nom-almatin.mp3',
      'nom-almubdi.mp3',
      'nom-almudhill.mp3',
      'nom-almughni.mp3',
      'nom-almuhaymin.mp3',
      'nom-almuhsi.mp3',
      'nom-almuhyi.mp3',
      'nom-almuid.mp3',
      'nom-almumin.mp3',
      'nom-almumit.mp3',
      'nom-almuntaqim.mp3',
      'nom-almuqaddim.mp3',
      'nom-almuqit.mp3',
      'nom-almuqsit.mp3',
      'nom-almuqtadir.mp3',
      'nom-almusawwir.mp3',
      'nom-almutaali.mp3',
      'nom-almutakabbir.mp3',
      'nom-alqabid.mp3',
      'nom-alqadir.mp3',
      'nom-alqahhar.mp3',
      'nom-alqawiyy.mp3',
      'nom-alqayyum.mp3',
      'nom-alquddus.mp3',
      'nom-alwadud.mp3',
      'nom-alwahhab.mp3',
      'nom-alwahid.mp3',
      'nom-alwakil.mp3',
      'nom-alwali.mp3',
      'nom-alwaliyy.mp3',
      'nom-alwasi.mp3',
      'nom-annur.mp3',
      'nom-arrahim.mp3',
      'nom-arrahman.mp3',
      'nom-arraqib.mp3',
      'nom-assabur.mp3',
      'nom-assalam.mp3',
      'nom-assamad.mp3',
      'nom-assami.mp3',
      'nom-attawwab.mp3',
      'nom-malikalmulk.mp3',
      'qaf-alif-son-prolonge.mp3',
      'qaf-damma-son-court.mp3',
      'qaf-fatha-son-court.mp3',
      'qaf-kasra-son-court.mp3',
      'qaf-waw-son-prolonge.mp3',
      'qaf-ya-son-prolonge.mp3',
      'sad-alif-son-prolonge.mp3',
      'sad-damma-son-court.mp3',
      'sad-fatha-son-court.mp3',
      'sad-kasra-son-court.mp3',
      'sad-waw-son-prolonge.mp3',
      'sad-ya-son-prolonge.mp3',
      'sin-alif-son-prolonge.mp3',
      'sin-waw-son-prolonge.mp3',
      'sin-ya-son-prolonge.mp3',
      'ta-alif-son-prolonge.mp3',
      'ta-damma-son-court.mp3',
      'ta-fatha-son-court.mp3',
      'ta-kasra-son-court.mp3',
      'ta-waw-son-prolonge.mp3',
      'ta-ya-son-prolonge.mp3',
      'tta-alif-son-prolonge.mp3',
      'tta-damma-son-court.mp3',
      'tta-fatha-son-court.mp3',
      'tta-kasra-son-court.mp3',
      'tta-waw-son-prolonge.mp3',
      'tta-ya-son-prolonge.mp3',
      'voyelle-a.mp3',
      'voyelle-i.mp3',
      'voyelle-ou.mp3',
      /* 16/08 — les prises de Myriam remplacent des
         fichiers déjà servis : sans cette liste, les appareils qui les ont entendus
         garderaient l'ancienne voix à vie (cache MEDIA, jamais purgé). */
      'dal-alif-son-prolonge.mp3',
      'dal-damma-son-court.mp3',
      'dal-fatha-son-court.mp3',
      'dal-kasra-son-court.mp3',
      'dal-waw-son-prolonge.mp3',
      'dal-ya-son-prolonge.mp3',
      'kaf-alif-son-prolonge.mp3',
      'kaf-damma-son-court.mp3',
      'kaf-fatha-son-court.mp3',
      'kaf-kasra-son-court.mp3',
      'kaf-waw-son-prolonge.mp3',
      'lettre-dal-nom.mp3',
      'lettre-dal-nom-f.mp3',
      'lettre-dha-nom.mp3',
      'lettre-dha-nom-f.mp3',
      'lettre-fa-nom.mp3',
      'lettre-jim-nom.mp3',
      'lettre-jim-nom-f.mp3',
      'lettre-kaf-nom.mp3',
      'lettre-kaf-nom-f.mp3',
      'lettre-kha-nom.mp3',
      'lettre-kha-nom-f.mp3',
      'lettre-shin-nom.mp3',
      'lettre-shin-nom-f.mp3',
      'lettre-sin-nom.mp3',
      'lettre-sin-nom-f.mp3',
      'lettre-tha-nom.mp3',
      'lettre-tha-nom-f.mp3',
      'lettre-zay-nom.mp3',
      'lettre-zay-nom-f.mp3',
      'mot-albab-f.mp3',
      'mot-albayt-f.mp3',
      'mot-aldalw-f.mp3',
      'mot-aldar-f.mp3',
      'mot-aldhahab-f.mp3',
      'mot-alhabl-f.mp3',
      'mot-alhimar-f.mp3',
      'mot-alnahl-f.mp3',
      'mot-alqalam-f.mp3',
      'mot-alqamar-f.mp3',
      'mot-alrumman-f.mp3',
      'mot-altayr-f.mp3',
      'mot-altin-f.mp3',
      'mot-alyad-f.mp3',
      'mot-annas.mp3',
      'mot-annas-f.mp3',
      'mot-bayt-f.mp3',
      'mot-bismi.mp3',
      'mot-bismi-f.mp3',
      'mot-dalw-f.mp3',
      'mot-dar-f.mp3',
      'mot-dars.mp3',
      'mot-dars-f.mp3',
      'mot-dhahab-f.mp3',
      'mot-din.mp3',
      'mot-din-f.mp3',
      'mot-habl-f.mp3',
      'mot-himar-f.mp3',
      'mot-iyyaka.mp3',
      'mot-iyyaka-f.mp3',
      'mot-karim.mp3',
      'mot-karim-f.mp3',
      'mot-kasaba.mp3',
      'mot-maalik.mp3',
      'mot-maalik-f.mp3',
      'mot-malik.mp3',
      'mot-malik-f.mp3',
      'mot-naabudu.mp3',
      'mot-naabudu-f.mp3',
      'mot-nahl-f.mp3',
      'mot-qalam-f.mp3',
      'mot-qamar-f.mp3',
      'mot-rumman-f.mp3',
      'mot-tayr-f.mp3',
      'mot-tin-f.mp3',
      'mot-yad-f.mp3',
      'sin-damma-son-court.mp3',
      'sin-fatha-son-court.mp3',
      'sin-kasra-son-court.mp3',
      /* 16/08 — les prises de Myriam remplacent des
         fichiers déjà servis : sans cette liste, les appareils qui les ont entendus
         garderaient l'ancienne voix à vie (cache MEDIA, jamais purgé). */
      'lettre-ba-nom.mp3',
      'lettre-ba-nom-f.mp3',
      'lettre-nun-nom.mp3',
      'lettre-nun-nom-f.mp3',
      'lettre-ra-nom.mp3',
      'lettre-ra-nom-f.mp3',
      'lettre-ya-nom.mp3',
      'lettre-ya-nom-f.mp3',
      'mot-addallin.mp3',
      'mot-almaghdub.mp3',
      'mot-almaghdub-f.mp3',
      'mot-alrumman.mp3',
      'mot-bab.mp3',
      'mot-bab-f.mp3',
      /* 01/09 — mot-bi.mp3 RECOUPÉ sous le MÊME nom (0,78 s au lieu de 1,38 s :
         la voix est intacte au bit près, on a retiré le silence et le clic de
         souris que le rogneur du studio avait laissés — sa bouffée faisait
         200 ms, au-dessus du seuil de 120 ms qu'il sait reconnaître).
         ⚠️ IL EST PARTI EN PRODUCTION UNE HEURE PLUS TÔT, DANS LE PRÉ-CACHE DE
         SW v169 : sans cette ligne, tout appareil ayant installé v169 garderait
         l'ancienne prise À VIE (le cache MEDIA n'est jamais purgé). C'est
         exactement l'incident du 08/08 — le « Mehdi » de la récompense, qui
         était un fichier remplacé sous le même nom et embaumé par ce cache. */
      'mot-bi.mp3',
    ]
      .map(f=>m.delete('audios-app-alaq/'+f,{ignoreSearch:true})));
    /* 24/08 — les 4 mp4 de l'écriture guidée U9 (écran 6/7, disque 1), réécrits
       SOUS LE MÊME NOM plusieurs fois dans la même journée pendant la mise au
       point (fond vert non détouré, puis mauvais recadrage/zoom, puis liseré
       résiduel en bas de cadre) : exactement le cas que cette purge ciblée
       existe pour couvrir — un appareil qui a ouvert le disque 1 CE jour-là a
       pu mettre en cache une version cassée, `MEDIA` ne l'aurait jamais lâchée. */
    await Promise.all(['ecrire-sombre-bg.mp4','ecrire-clair-bg.mp4',
      'ecrire-sombre-panel.mp4','ecrire-clair-panel.mp4']
      .map(f=>m.delete('images-app-alaq/u9/'+f,{ignoreSearch:true})));
    self.clients.claim();
  })());
});
self.addEventListener('fetch',e=>{
  /* ⚠️ LES REQUÊTES « Range » NE SE INTERCEPTENT JAMAIS (10/08). Safari streame l'audio
     par tranches (Range: bytes=…) et exige un 206 ; le cache répondait un 200 complet
     → AVFoundation refuse → « les sons de récitateurs ne fonctionnent pas » (Myriam),
     alors que le CDN répond 200 partout. On laisse ces requêtes filer au réseau. */
  if(e.request.headers.get('range'))return;
  const url=new URL(e.request.url);
  // navigation / index : réseau d'abord, cache en secours
  if(e.request.mode==='navigate'||url.pathname.endsWith('/index.html')||url.pathname==='/'){
    e.respondWith((async()=>{
      const c=await caches.open(CACHE);
      const hit=await c.match('index.html');
      // rafraîchissement SILENCIEUX en arrière-plan : la prochaine ouverture aura la nouvelle version
      const frais=fetch(e.request).then(r=>{if(r&&r.ok)c.put('index.html',r.clone());return r;}).catch(()=>null); // jamais un 500/portail captif en cache (audit 10/08)
      // le cache d'abord : l'app s'ouvre TOUT DE SUITE, même si le réseau traîne
      return hit || (await frais) || (await caches.match('.')) || Response.error();
    })());
    return;
  }
  // audios, polices Google, récitation, icônes : cache d'abord
  const cacheFirst=url.pathname.indexOf('/audios-app-alaq/')>=0
    ||url.hostname==='fonts.googleapis.com'||url.hostname==='fonts.gstatic.com'||url.hostname==='cdn.jsdelivr.net'
    ||url.hostname==='cdn.islamic.network'  // la récitation streamée : mise en cache côté client, comme leurs conditions le demandent
    ||/\.(png|jpe?g|webp|mp3|mp4|woff2?)$/.test(url.pathname); // webp ajouté le 27/08 (épi animé) — un oubli du régime cache-d'abord, corrigé au passage
  if(cacheFirst){
    e.respondWith((async()=>{
      const hit=await caches.match(e.request);
      if(hit)return hit;
      try{
        const r=await fetch(e.request);
        // les IMAGES vont dans leur cache versionné ; sons, polices, récitation dans MEDIA
        if(r&&(r.ok||r.type==='opaque')){
          const img=/\.(png|jpe?g|webp|gif)$/.test(url.pathname);
          const c=await caches.open(img?IMGCACHE:MEDIA);c.put(e.request,r.clone());
        }
        return r;
      }catch(_){return Response.error();}
    })());
  }
});
